### PR TITLE
Resolve relative symlink paths correctly

### LINKED ISSUE #1000: Studio Site stopped working after software update - Failed to start the site server
### Quick summary

My local Studio site stopped working after updating Studio to the latest version (v1.3.5)

When I click on "Start" I get the following error:

Image

If I try to export the site I get the following error:

Image

If I delete the site from Studio (without removing the files) and try to create a new from the same folder I get the following error:

Image

### Steps to reproduce

1. Start the Studio Site
1. Update the Studio software to latest version (v1.3.5)
1. Stop the site and start it again

### What you expected to happen

The site should start without errors

### What actually happened

I get errors described above

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

### Logs or notes

These are the logs I get in Studio

<details>
<summary>See logs at <code>/Users/juanmanuelgarrido/Library/Logs/Studio/studio-20250304.0.log</code></summary>

```
[2025-03-04T09:41:46.858Z][info][main] Starting new session
[2025-03-04T09:41:46.862Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-03-04T09:41:46.970Z][info][main] App version: 1.3.4
[2025-03-04T09:41:46.971Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-03-04T09:41:46.976Z][info][main] Local timezone: Europe/London
[2025-03-04T09:41:46.976Z][info][main] App locale: en-GB
[2025-03-04T09:41:46.976Z][info][main] System locale: en-GB
[2025-03-04T09:41:46.976Z][info][main] Used language: en
[2025-03-04T09:41:46.981Z][info][main] Setting Sentry user ID: 8477d4f5-126c-4ef0-9838-8bdf1d9823d1
[2025-03-04T09:41:47.421Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-03-04T09:41:47.724Z][info][main] SQLite folder already exists. Skipping download.
[2025-03-04T09:41:48.595Z][info][main] Stopped watching for file changes
[2025-03-04T09:41:48.986Z][info][main] SQLite Command is up to date.
[2025-03-04T09:41:50.023Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T09:41:50.193Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T09:41:50.194Z][info][site-server-process] mode: wordpress
[2025-03-04T09:41:50.194Z][info][site-server-process] php: 8.2
[2025-03-04T09:41:50.194Z][info][site-server-process] wp: latest
[2025-03-04T09:41:50.194Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T09:41:50.194Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T09:41:52.451Z][info][site-server-process] Server running at http://localhost:8883
[2025-03-04T09:41:53.924Z][info][main] Server started for 'WP Site - Data Layer'
[2025-03-04T10:41:47.384Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-03-04T11:41:47.642Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-03-04T11:41:48.598Z][info][main] Update available
[2025-03-04T11:41:48.599Z][info][main] Update available
[2025-03-04T11:42:32.930Z][info][main] Update has been downloaded
[2025-03-04T11:42:47.673Z][info][main] App is terminating[2025-03-04T11:42:57.604Z][info][main] Starting new session
[2025-03-04T11:42:57.607Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.5
[2025-03-04T11:42:57.679Z][info][main] App version: 1.3.5
[2025-03-04T11:42:57.679Z][info][main] Built from commit: 458f1c7cf7b42c9760975b040a2c2b2070fe396d
[2025-03-04T11:42:57.680Z][info][main] Local timezone: Europe/London
[2025-03-04T11:42:57.680Z][info][main] App locale: en-GB
[2025-03-04T11:42:57.680Z][info][main] System locale: en-GB
[2025-03-04T11:42:57.680Z][info][main] Used language: en
[2025-03-04T11:42:57.683Z][info][main] Setting Sentry user ID: 8477d4f5-126c-4ef0-9838-8bdf1d9823d1
[2025-03-04T11:42:58.180Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:42:58.475Z][info][main] SQLite folder already exists. Skipping download.
[2025-03-04T11:42:59.214Z][info][main] Stopped watching for file changes
[2025-03-04T11:42:59.638Z][info][main] SQLite Command is up to date.
[2025-03-04T11:43:16.668Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T11:43:16.877Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T11:43:16.877Z][info][site-server-process] mode: wordpress
[2025-03-04T11:43:16.877Z][info][site-server-process] php: 8.2
[2025-03-04T11:43:16.877Z][info][site-server-process] wp: latest
[2025-03-04T11:43:16.877Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:43:16.878Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:43:16.963Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832771)
    at Generator.next (<anonymous>)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828635
    at new Promise (<anonymous>)
    at n (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828380)
    at t.SymlinkManager.mountTarget (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832514)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832470)
    at Generator.next (<anonymous>)
    at i (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828437)
[2025-03-04T11:43:17.252Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T11:43:21.333Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T11:43:21.545Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T11:43:21.546Z][info][site-server-process] mode: wordpress
[2025-03-04T11:43:21.546Z][info][site-server-process] php: 8.2
[2025-03-04T11:43:21.546Z][info][site-server-process] wp: latest
[2025-03-04T11:43:21.546Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:43:21.546Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:43:21.618Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832771)
    at Generator.next (<anonymous>)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828635
    at new Promise (<anonymous>)
    at n (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828380)
    at t.SymlinkManager.mountTarget (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832514)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832470)
    at Generator.next (<anonymous>)
    at i (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828437)
[2025-03-04T11:43:21.898Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T11:44:14.346Z][info][main] App is terminating[2025-03-04T11:44:20.309Z][info][main] Starting new session
[2025-03-04T11:44:20.311Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.5
[2025-03-04T11:44:20.377Z][info][main] App version: 1.3.5
[2025-03-04T11:44:20.378Z][info][main] Built from commit: 458f1c7cf7b42c9760975b040a2c2b2070fe396d
[2025-03-04T11:44:20.379Z][info][main] Local timezone: Europe/London
[2025-03-04T11:44:20.379Z][info][main] App locale: en-GB
[2025-03-04T11:44:20.379Z][info][main] System locale: en-GB
[2025-03-04T11:44:20.379Z][info][main] Used language: en
[2025-03-04T11:44:20.381Z][info][main] Setting Sentry user ID: 8477d4f5-126c-4ef0-9838-8bdf1d9823d1
[2025-03-04T11:44:20.776Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:44:21.080Z][info][main] SQLite folder already exists. Skipping download.
[2025-03-04T11:44:21.824Z][info][main] Stopped watching for file changes
[2025-03-04T11:44:22.201Z][info][main] SQLite Command is up to date.
[2025-03-04T11:44:23.346Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T11:44:23.558Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T11:44:23.558Z][info][site-server-process] mode: wordpress
[2025-03-04T11:44:23.558Z][info][site-server-process] php: 8.2
[2025-03-04T11:44:23.558Z][info][site-server-process] wp: latest
[2025-03-04T11:44:23.559Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:44:23.559Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:44:23.632Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832771)
    at Generator.next (<anonymous>)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828635
    at new Promise (<anonymous>)
    at n (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828380)
    at t.SymlinkManager.mountTarget (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832514)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832470)
    at Generator.next (<anonymous>)
    at i (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828437)
[2025-03-04T11:44:23.919Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T11:44:37.003Z][info][main] Starting server for 'My Demo Site '
[2025-03-04T11:44:37.216Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/my-demo-site
[2025-03-04T11:44:37.217Z][info][site-server-process] mode: wordpress
[2025-03-04T11:44:37.217Z][info][site-server-process] php: 8.2
[2025-03-04T11:44:37.217Z][info][site-server-process] wp: latest
[2025-03-04T11:44:37.217Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:44:37.217Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:44:38.928Z][info][site-server-process] Server running at http://localhost:8882
[2025-03-04T11:44:40.335Z][info][main] Server started for 'My Demo Site '
[2025-03-04T11:44:41.880Z][info][main] Stopping server with ID 710ee7c6-3a97-4100-bbe7-e0b1fc9b8fcc
[2025-03-04T11:44:41.882Z][info][site-server-process] Server stopped
[2025-03-04T11:44:55.694Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T11:44:55.905Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T11:44:55.906Z][info][site-server-process] mode: wordpress
[2025-03-04T11:44:55.906Z][info][site-server-process] php: 8.2
[2025-03-04T11:44:55.906Z][info][site-server-process] wp: latest
[2025-03-04T11:44:55.906Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:44:55.906Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:44:55.978Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832771)
    at Generator.next (<anonymous>)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828635
    at new Promise (<anonymous>)
    at n (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828380)
    at t.SymlinkManager.mountTarget (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832514)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832470)
    at Generator.next (<anonymous>)
    at i (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828437)
[2025-03-04T11:44:56.259Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T11:48:27.211Z][info][main] Starting server for 'WP Site - Data Layer'
[2025-03-04T11:48:27.423Z][info][site-server-process] directory: /Users/juanmanuelgarrido/Studio/wp-site-data-layer
[2025-03-04T11:48:27.423Z][info][site-server-process] mode: wordpress
[2025-03-04T11:48:27.423Z][info][site-server-process] php: 8.2
[2025-03-04T11:48:27.423Z][info][site-server-process] wp: latest
[2025-03-04T11:48:27.423Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-03-04T11:48:27.423Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-03-04T11:48:27.493Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832771)
    at Generator.next (<anonymous>)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828635
    at new Promise (<anonymous>)
    at n (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828380)
    at t.SymlinkManager.mountTarget (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832514)
    at t.SymlinkManager.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:832470)
    at Generator.next (<anonymous>)
    at i (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:828437)
[2025-03-04T11:48:27.773Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T11:50:50.768Z][erro][main] Could not create directory "../acorn/bin/acorn": Invalid argument.
[2025-03-04T11:50:50.772Z][erro][main] Error occurred in handler for 'exportSite': TypeError: Cannot read properties of undefined (reading 'message')
    at L.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2754670)
    at Generator.throw (<anonymous>)
    at s (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2749896)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2025-03-04T11:50:50.775Z][info][main] Backup created at: /Users/juanmanuelgarrido/Desktop/studio-backup-wp-site-data-layer-2025-03-04-11-50-44.zip
[2025-03-04T12:00:50.769Z][info][main] Deleting site d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T12:00:50.772Z][info][main] Stopping server with ID d81eabd2-e009-48c2-bf6c-902c910c2ac2
[2025-03-04T12:00:50.865Z][info][main] Killed processes using port 8883
[2025-03-04T12:01:11.576Z][erro][main] Could not create directory "../acorn/bin/acorn": Invalid argument.
[2025-03-04T12:01:11.577Z][erro][main] Error occurred in handler for 'createSite': TypeError: Cannot read properties of undefined (reading 'message')
    at L.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2754670)
    at Generator.throw (<anonymous>)
    at s (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2749896)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2025-03-04T12:01:11.578Z][erro][ren1] Failed to create site

```

</details>

And this the structure of files I have on the site's source folder:

<details>
<summary>See structure of files under <code>/Users/juanmanuelgarrido/STUDIO/wp-site-data-layer</code></summary>

```
⬢  wp-site-data-layer  pwd
/Users/juanmanuelgarrido/STUDIO/wp-site-data-layer
⬢  wp-site-data-layer  tree -a -L 2 --gitignore -I .git -I node_modules
.
├── .DS_Store
├── index.php
├── license.txt
├── readme.html
├── wp-activate.php
├── wp-admin
│   ├── .DS_Store
│   ├── about.php
│   ├── admin-ajax.php
│   ├── admin-footer.php
│   ├── admin-functions.php
│   ├── admin-header.php
│   ├── admin-post.php
│   ├── admin.php
│   ├── async-upload.php
│   ├── authorize-application.php
│   ├── comment.php
│   ├── contribute.php
│   ├── credits.php
│   ├── css
│   ├── custom-background.php
│   ├── custom-header.php
│   ├── customize.php
│   ├── edit-comments.php
│   ├── edit-form-advanced.php
│   ├── edit-form-blocks.php
│   ├── edit-form-comment.php
│   ├── edit-link-form.php
│   ├── edit-tag-form.php
│   ├── edit-tags.php
│   ├── edit.php
│   ├── erase-personal-data.php
│   ├── export-personal-data.php
│   ├── export.php
│   ├── freedoms.php
│   ├── images
│   ├── import.php
│   ├── includes
│   ├── index.php
│   ├── install-helper.php
│   ├── install.php
│   ├── js
│   ├── link-add.php
│   ├── link-manager.php
│   ├── link-parse-opml.php
│   ├── link.php
│   ├── load-scripts.php
│   ├── load-styles.php
│   ├── maint
│   ├── media-new.php
│   ├── media-upload.php
│   ├── media.php
│   ├── menu-header.php
│   ├── menu.php
│   ├── moderation.php
│   ├── ms-admin.php
│   ├── ms-delete-site.php
│   ├── ms-edit.php
│   ├── ms-options.php
│   ├── ms-sites.php
│   ├── ms-themes.php
│   ├── ms-upgrade-network.php
│   ├── ms-users.php
│   ├── my-sites.php
│   ├── nav-menus.php
│   ├── network
│   ├── network.php
│   ├── options-discussion.php
│   ├── options-general.php
│   ├── options-head.php
│   ├── options-media.php
│   ├── options-permalink.php
│   ├── options-privacy.php
│   ├── options-reading.php
│   ├── options-writing.php
│   ├── options.php
│   ├── plugin-editor.php
│   ├── plugin-install.php
│   ├── plugins.php
│   ├── post-new.php
│   ├── post.php
│   ├── press-this.php
│   ├── privacy-policy-guide.php
│   ├── privacy.php
│   ├── profile.php
│   ├── revision.php
│   ├── setup-config.php
│   ├── site-editor.php
│   ├── site-health-info.php
│   ├── site-health.php
│   ├── term.php
│   ├── theme-editor.php
│   ├── theme-install.php
│   ├── themes.php
│   ├── tools.php
│   ├── update-core.php
│   ├── update.php
│   ├── upgrade-functions.php
│   ├── upgrade.php
│   ├── upload.php
│   ├── user
│   ├── user-edit.php
│   ├── user-new.php
│   ├── users.php
│   ├── widgets-form-blocks.php
│   ├── widgets-form.php
│   └── widgets.php
├── wp-blog-header.php
├── wp-comments-post.php
├── wp-config-sample.php
├── wp-config.php
├── wp-content
│   ├── .DS_Store
│   ├── database
│   ├── db.php
│   ├── fonts
│   ├── index.php
│   ├── mu-plugins
│   ├── plugins
│   ├── themes
│   ├── upgrade
│   └── uploads
├── wp-cron.php
├── wp-includes
│   ├── .DS_Store
│   ├── ID3
│   ├── IXR
│   ├── PHPMailer
│   ├── Requests
│   ├── SimplePie
│   ├── Text
│   ├── admin-bar.php
│   ├── assets
│   ├── atomlib.php
│   ├── author-template.php
│   ├── block-bindings
│   ├── block-bindings.php
│   ├── block-editor.php
│   ├── block-i18n.json
│   ├── block-patterns
│   ├── block-patterns.php
│   ├── block-supports
│   ├── block-template-utils.php
│   ├── block-template.php
│   ├── blocks
│   ├── blocks.php
│   ├── bookmark-template.php
│   ├── bookmark.php
│   ├── cache-compat.php
│   ├── cache.php
│   ├── canonical.php
│   ├── capabilities.php
│   ├── category-template.php
│   ├── category.php
│   ├── certificates
│   ├── class-IXR.php
│   ├── class-avif-info.php
│   ├── class-feed.php
│   ├── class-http.php
│   ├── class-json.php
│   ├── class-oembed.php
│   ├── class-phpass.php
│   ├── class-phpmailer.php
│   ├── class-pop3.php
│   ├── class-requests.php
│   ├── class-simplepie.php
│   ├── class-smtp.php
│   ├── class-snoopy.php
│   ├── class-walker-category-dropdown.php
│   ├── class-walker-category.php
│   ├── class-walker-comment.php
│   ├── class-walker-nav-menu.php
│   ├── class-walker-page-dropdown.php
│   ├── class-walker-page.php
│   ├── class-wp-admin-bar.php
│   ├── class-wp-ajax-response.php
│   ├── class-wp-application-passwords.php
│   ├── class-wp-block-bindings-registry.php
│   ├── class-wp-block-bindings-source.php
│   ├── class-wp-block-editor-context.php
│   ├── class-wp-block-list.php
│   ├── class-wp-block-metadata-registry.php
│   ├── class-wp-block-parser-block.php
│   ├── class-wp-block-parser-frame.php
│   ├── class-wp-block-parser.php
│   ├── class-wp-block-pattern-categories-registry.php
│   ├── class-wp-block-patterns-registry.php
│   ├── class-wp-block-styles-registry.php
│   ├── class-wp-block-supports.php
│   ├── class-wp-block-template.php
│   ├── class-wp-block-templates-registry.php
│   ├── class-wp-block-type-registry.php
│   ├── class-wp-block-type.php
│   ├── class-wp-block.php
│   ├── class-wp-classic-to-block-menu-converter.php
│   ├── class-wp-comment-query.php
│   ├── class-wp-comment.php
│   ├── class-wp-customize-control.php
│   ├── class-wp-customize-manager.php
│   ├── class-wp-customize-nav-menus.php
│   ├── class-wp-customize-panel.php
│   ├── class-wp-customize-section.php
│   ├── class-wp-customize-setting.php
│   ├── class-wp-customize-widgets.php
│   ├── class-wp-date-query.php
│   ├── class-wp-dependencies.php
│   ├── class-wp-dependency.php
│   ├── class-wp-duotone.php
│   ├── class-wp-editor.php
│   ├── class-wp-embed.php
│   ├── class-wp-error.php
│   ├── class-wp-exception.php
│   ├── class-wp-fatal-error-handler.php
│   ├── class-wp-feed-cache-transient.php
│   ├── class-wp-feed-cache.php
│   ├── class-wp-hook.php
│   ├── class-wp-http-cookie.php
│   ├── class-wp-http-curl.php
│   ├── class-wp-http-encoding.php
│   ├── class-wp-http-ixr-client.php
│   ├── class-wp-http-proxy.php
│   ├── class-wp-http-requests-hooks.php
│   ├── class-wp-http-requests-response.php
│   ├── class-wp-http-response.php
│   ├── class-wp-http-streams.php
│   ├── class-wp-http.php
│   ├── class-wp-image-editor-gd.php
│   ├── class-wp-image-editor-imagick.php
│   ├── class-wp-image-editor.php
│   ├── class-wp-list-util.php
│   ├── class-wp-locale-switcher.php
│   ├── class-wp-locale.php
│   ├── class-wp-matchesmapregex.php
│   ├── class-wp-meta-query.php
│   ├── class-wp-metadata-lazyloader.php
│   ├── class-wp-navigation-fallback.php
│   ├── class-wp-network-query.php
│   ├── class-wp-network.php
│   ├── class-wp-object-cache.php
│   ├── class-wp-oembed-controller.php
│   ├── class-wp-oembed.php
│   ├── class-wp-paused-extensions-storage.php
│   ├── class-wp-plugin-dependencies.php
│   ├── class-wp-post-type.php
│   ├── class-wp-post.php
│   ├── class-wp-query.php
│   ├── class-wp-recovery-mode-cookie-service.php
│   ├── class-wp-recovery-mode-email-service.php
│   ├── class-wp-recovery-mode-key-service.php
│   ├── class-wp-recovery-mode-link-service.php
│   ├── class-wp-recovery-mode.php
│   ├── class-wp-rewrite.php
│   ├── class-wp-role.php
│   ├── class-wp-roles.php
│   ├── class-wp-script-modules.php
│   ├── class-wp-scripts.php
│   ├── class-wp-session-tokens.php
│   ├── class-wp-simplepie-file.php
│   ├── class-wp-simplepie-sanitize-kses.php
│   ├── class-wp-site-query.php
│   ├── class-wp-site.php
│   ├── class-wp-styles.php
│   ├── class-wp-tax-query.php
│   ├── class-wp-taxonomy.php
│   ├── class-wp-term-query.php
│   ├── class-wp-term.php
│   ├── class-wp-text-diff-renderer-inline.php
│   ├── class-wp-text-diff-renderer-table.php
│   ├── class-wp-textdomain-registry.php
│   ├── class-wp-theme-json-data.php
│   ├── class-wp-theme-json-resolver.php
│   ├── class-wp-theme-json-schema.php
│   ├── class-wp-theme-json.php
│   ├── class-wp-theme.php
│   ├── class-wp-token-map.php
│   ├── class-wp-user-meta-session-tokens.php
│   ├── class-wp-user-query.php
│   ├── class-wp-user-request.php
│   ├── class-wp-user.php
│   ├── class-wp-walker.php
│   ├── class-wp-widget-factory.php
│   ├── class-wp-widget.php
│   ├── class-wp-xmlrpc-server.php
│   ├── class-wp.php
│   ├── class-wpdb.php
│   ├── class.wp-dependencies.php
│   ├── class.wp-scripts.php
│   ├── class.wp-styles.php
│   ├── comment-template.php
│   ├── comment.php
│   ├── compat.php
│   ├── cron.php
│   ├── css
│   ├── customize
│   ├── date.php
│   ├── default-constants.php
│   ├── default-filters.php
│   ├── default-widgets.php
│   ├── deprecated.php
│   ├── embed-template.php
│   ├── embed.php
│   ├── error-protection.php
│   ├── feed-atom-comments.php
│   ├── feed-atom.php
│   ├── feed-rdf.php
│   ├── feed-rss.php
│   ├── feed-rss2-comments.php
│   ├── feed-rss2.php
│   ├── feed.php
│   ├── fonts
│   ├── fonts.php
│   ├── formatting.php
│   ├── functions.php
│   ├── functions.wp-scripts.php
│   ├── functions.wp-styles.php
│   ├── general-template.php
│   ├── global-styles-and-settings.php
│   ├── html-api
│   ├── http.php
│   ├── https-detection.php
│   ├── https-migration.php
│   ├── images
│   ├── interactivity-api
│   ├── js
│   ├── kses.php
│   ├── l10n
│   ├── l10n.php
│   ├── link-template.php
│   ├── load.php
│   ├── locale.php
│   ├── media-template.php
│   ├── media.php
│   ├── meta.php
│   ├── ms-blogs.php
│   ├── ms-default-constants.php
│   ├── ms-default-filters.php
│   ├── ms-deprecated.php
│   ├── ms-files.php
│   ├── ms-functions.php
│   ├── ms-load.php
│   ├── ms-network.php
│   ├── ms-settings.php
│   ├── ms-site.php
│   ├── nav-menu-template.php
│   ├── nav-menu.php
│   ├── option.php
│   ├── php-compat
│   ├── pluggable-deprecated.php
│   ├── pluggable.php
│   ├── plugin.php
│   ├── pomo
│   ├── post-formats.php
│   ├── post-template.php
│   ├── post-thumbnail-template.php
│   ├── post.php
│   ├── query.php
│   ├── registration-functions.php
│   ├── registration.php
│   ├── rest-api
│   ├── rest-api.php
│   ├── revision.php
│   ├── rewrite.php
│   ├── robots-template.php
│   ├── rss-functions.php
│   ├── rss.php
│   ├── script-loader.php
│   ├── script-modules.php
│   ├── session.php
│   ├── shortcodes.php
│   ├── sitemaps
│   ├── sitemaps.php
│   ├── sodium_compat
│   ├── spl-autoload-compat.php
│   ├── style-engine
│   ├── style-engine.php
│   ├── taxonomy.php
│   ├── template-canvas.php
│   ├── template-loader.php
│   ├── template.php
│   ├── theme-compat
│   ├── theme-i18n.json
│   ├── theme-previews.php
│   ├── theme-templates.php
│   ├── theme.json
│   ├── theme.php
│   ├── update.php
│   ├── user.php
│   ├── vars.php
│   ├── version.php
│   ├── widgets
│   ├── widgets.php
│   ├── wp-db.php
│   └── wp-diff.php
├── wp-links-opml.php
├── wp-load.php
├── wp-login.php
├── wp-mail.php
├── wp-settings.php
├── wp-signup.php
├── wp-trackback.php
└── xmlrpc.php

46 directories, 356 files
```
</details>

### LINKED ISSUE #1006: Error "Could not create directory '../acorn/bin/acorn': Invalid argument" when starting site (works fine in v1.3.4)
### Quick summary

After updating beyond version 1.3.5, attempting to start an existing WordPress site in Studio fails with the following error:

`Failed to start the site server
Please verify your site’s local path directory contains the standard WordPress installation files and try again. If this problem persists, please contact support.
Could not create directory "../acorn/bin/acorn": Invalid argument.
`

## Additional Context

- Downgrading to [Studio v1.3.4](https://cdn.a8c-ci.services/studio/studio-darwin-arm64-v1.3.4.dmg) (Apple Silicon build) immediately resolves the issue, so this appears to be a regression introduced after that version.
- The error references an acorn directory with a relative path (../acorn/bin/acorn), which may indicate a path resolution or permissions issue in the newer releases.
- Let me know if additional logs, environment details, or configuration files would help troubleshoot further.

## Screenshots

Please see the attached screenshot for the pop-up error message:

Image

### Steps to reproduce

- Open Studio (version newer than 1.3.5).
- Attempt to start a previously existing WordPress site (one that worked in 1.3.5 or earlier).
- Observe the error pop-up: "Failed to start the site server."
- Check the logs to see the Could not create directory "../acorn/bin/acorn": Invalid argument. message.

### What you expected to happen

The site should start normally without errors or attempts to create invalid directory paths, as it did in v1.3.4.

### What actually happened

The site failed to start, and Studio threw an error stating it couldn't create the directory "../acorn/bin/acorn" due to an invalid argument.

### Impact

One

### Available workarounds?

No available workarounds. The app becomes unusable without downgrading.

### Platform

MacBook Air (Apple Silicon), PHP 8.1

### Logs or notes

[2025-03-04T21:53:33.944Z][erro][main] Error occurred in handler for 'startServer': Error: Could not create directory "../acorn/bin/acorn": Invalid argument.
    at n.value (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2789689)
    at PHP.mkdir (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:2806061)
    ...

### PR DESCRIPTION
**Pull request by fredrikekelund**
## Related issues

- Fixes https://github.com/Automattic/studio/issues/1000 and https://github.com/Automattic/studio/issues/1006

## Proposed Changes

First, a quick recap of how `SymlinkManager` works. Symlinks are technically preserved when mounting the site directory in Playground's virtual file system. However, symlinks are in reality just a special type of file with a target path, and if the target path is outside the document root, it's not accessible in Playground's FS. This is where `SymlinkManager` comes in – it creates a directory inside Playground's FS at the target path and mounts the target path from the host filesystem there.

This PR specifically fixes an issue that was introduced when we recently upgraded our Playground dependencies (https://github.com/Automattic/studio/pull/959). After the upgrade, the `php.readlink` function started returning the correct value, which is the symlink's exact, unresolved target path (i.e. it suddenly returned relative paths sometimes).

This PR changes the `SymlinkManager::addSymlink` method to resolve the path returned from `php.readlink` relative to the directory where the symlink lives (i.e. how symlinks are normally handled). 

<del>I've also added a `SymlinkManager::isTargetInsideDocumentRoot` method that allows us to skip mounting symlink target paths that are already accessible inside the document root. Should make `SymlinkManager` more efficient.</del><ins>After working on fixing the failing tests, I realized that `SymlinkManager::mountTarget` already has this performance optimization in that it checks if the file or directory already exists in the Playground FS before attempting to mount it.</ins>

## Testing Instructions

First, let's test the specific case that was reported to us:

1. Have a Studio site
2. Download [this plugin](https://github.com/juanma-wp/wp-data-layer-app-pages) and unpack it to `wp-content/plugins`
3. Run `npm install` inside the plugin directory
4. Start the Studio site and ensure that it doesn't encounter any errors

Secondly, let's test a typical symlink targeting a directory outside the document root:

1. Have a Studio site where Yoast SEO is not already installed
2. Download [Yoast SEO](https://wordpress.org/plugins/wordpress-seo) and extract it to `~/wordpress-seo`
3. In your site's `wp-content/plugins` directory, run `ln -s ~/wordpress-seo`
4. Start the Studio site
5. Navigate to `/wp-admin/plugins.php`
6. Ensure that the Yoast SEO plugin is available and that you can activate it without error

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/lib/symlink-manager.ts [hunk 1]
```diff
@@ -195,6 +210,9 @@ export class SymlinkManager {
 			vfsTarget,
 			createNodeFsMountHandler( hostTarget )
 		);
+		// For some reason, we must access the target directory after mounting it, otherwise the
+		// mount will not work.
+		this.php.listFiles( vfsTarget );
```
Comment (fredrikekelund) [inline src/lib/symlink-manager.ts:201]: @bgrgicak @adamziel @ashfame, I'm not sure why this is needed, but the Yoast SEO test case (see PR description) didn't work without it in my testing. Any idea why that's the case..?

File: src/lib/symlink-manager.ts [hunk 2]
```diff
@@ -152,18 +161,24 @@ export class SymlinkManager {
...
+		const vfsPath = path.posix.resolve( this.documentRoot, filename );
 
 		// Double check to ensure the symlink exists
 		if ( ! this.php.fileExists( vfsPath ) ) {
 			return;
 		}
 
 		// Get the realpath of the symlink within the PHP runtime.
-		const vfsTarget = this.php.readlink( vfsPath );
+		const vfsTarget = path.posix.resolve( path.dirname( vfsPath ), this.php.readlink( vfsPath ) );
```
Comment (fredrikekelund) [inline src/lib/symlink-manager.ts:163]: `php.realpath` does not accomplish the same thing (confirmed in my testing). I believe it just returns `false` because the target path does not yet exist at this point.

Comment (fredrikekelund) [reply src/lib/symlink-manager.ts:163]: To expand on this: `realpath` works as a more compact way of expressing this logic **if the target path is already within the document root**. If this is not the case, `realpath` returns false because the target does not yet exist (see [PHP docs](https://www.php.net/manual/en/function.realpath.php)). 

The `SymlinkManager::isTargetInsideDocumentRoot` added in this PR stems from the realization that if the target path is already within the document root, there's no need for `SymlinkManager` to intervene. This is a performance optimization that should help speed up server starts for sites with many symlinks.

File: src/lib/symlink-manager.ts (hunk 1 above)
Comment (wojtekn) [reply src/lib/symlink-manager.ts:201]: It continues to work for me when I comment out this line. Maybe it depends on the underlying filesystem and we use different ones?

**Comment by wojtekn** [comment]
It fixes both cases for me.

File: src/lib/symlink-manager.ts (hunk 2 above)
Comment (fredrikekelund) [reply src/lib/symlink-manager.ts:163]: Following up about `SymlinkManager::isTargetInsideDocumentRoot`: I realized that `SymlinkManager::mountTarget` already has this performance optimization in that it checks if the file or directory already exists in the Playground FS before attempting to mount it. Hence, I removed this method.

**Review by wojtekn — APPROVED** [review]

File: src/lib/symlink-manager.ts (hunk 1 above)
Comment (fredrikekelund) [reply src/lib/symlink-manager.ts:201]: To quickly double-check: did you restart the entire app after commenting out this line?

Comment (sejas) [reply src/lib/symlink-manager.ts:201]: I was able to mount and start a site with `wp-data-layer-app-pages` plugin without listing the files.

**Review by sejas — APPROVED** [review]
Solves the issue and I can start the site without any `../acorn/bin/acorn` symlink error. 👍

**Review by ivan-ottinger — APPROVED** [review]
The changes test well. I haven't been able to reproduce the issue anymore. 👍🏼 

Symlinked plugin works well as well.

I did not observe any regressions.

File: src/lib/symlink-manager.ts (hunk 1 above)
Comment (fredrikekelund) [reply src/lib/symlink-manager.ts:201]: Yeah, the `wp-data-layer-app-pages` test case works without this line for me, too. It's only the Yoast test case that was troublesome

Comment (fredrikekelund) [reply src/lib/symlink-manager.ts:201]: We may find that this line is unnecessary after further testing, but I have a hard time seeing how it would break anything, so I'll land the PR with this included and we can keep the discussion going after merging.

**Comment by adamziel** [comment]
Does that solve for Studio problems with symlinks?

**Comment by fredrikekelund** [comment]
@adamziel, not entirely. See https://github.com/Automattic/dotcom-forge/issues/10566 and https://github.com/Automattic/studio/issues/548. I'm anticipating that we'll need some assistance with Windows support – the issue description should give you a decent idea of what the problem is currently.
