### PR TITLE
Mount filesystems again when rotating PHP runtime instance

### LINKED ISSUE #516: Site no longer accessible after exactly 400 requests
### Quick summary

As i was doing some benchmark tests after we updated the version of Playground, I found that after exactly 400 requests the site is no longer accessible.

I pinned this down to our use of `rotatePHPRuntime` - this is a rotation mechanism that replaces the PHP instance with a fresh one after `n` events.  See [the Playground source code](https://github.com/WordPress/wordpress-playground/blob/trunk/packages/php-wasm/universal/src/lib/rotate-php-runtime.ts#L27) for more information.

In essence, the rotation mechanism is there to deal with memory leaks that could be imposed by third-party extensions that we use.

We use the `rotatePHPRuntime` when we create a PHP instance: [see here](https://github.com/Automattic/studio/blob/d98ea0fc1f5ef5da45e6e87db01a08b3d1428633/vendor/wp-now/src/wp-now.ts#L146)

While we successfully rotate PHP instances, those fresh instances come without any mounts leading to 404 not found responses. We need to ensure that if we choose to continue using the rotation mechanism, that we initialize new instances with the appropriate mounts.

Alternatively, we could consider to remove the rotation of PHP instances altogether, but we need to thoroughly test that this does not lead to performance and resource usage issues.

### Steps to reproduce

1. Start Studio site (but don't open it)
2. Run `ab -n 400 http://localhost:<port>` (Apache benchmarking tool)
3. Observe that it fails at exactly 398 requests.
4. Try to open the site and observe it responds with a not found 404 page. 

### What you expected to happen

The site should continue working after 400 requests

### What actually happened

The site stopped working after the 400th request.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform

Mac Silicon

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeroenpf**
Fixes #516

## Proposed Changes

When rotating an instance, the callback used by the rotation logic should prepare the filesystem and mount the required directories again as they are not retained. Only MEMFS mounts are carried over to the fresh instance but we are using NODEFS for most mounts.

To achieve this, i extracted some logic out of the huge main function `startWPNow` to make it reusable when creating the first instance AND during the rotation.

Not all logic needs to be executed again. We only care about the mounts and PHP settings.

## Testing Instructions

- Create a site
- Run `ab -n 500 http://localhost:<port>/`
- Wait for the 500 requests to run and ensure there are no failing requests
- Keep an eye on the console where you ran `npm start` when request 400 has been reached, you should see a log output telling you the PHP instance is being rotated.
- Observe that you can navigate the WordPress site and WP-admin without issues

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by kozer — APPROVED** [review]
Tested it and works as expected:
```
❯ ab -n 500 http://localhost:8885/


Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests

Completed 500 requests
Finished 500 requests
```
image

File: vendor/wp-now/src/wp-now.ts [hunk 1]
```diff
@@ -158,6 +129,55 @@ export default async function startWPNow(
...
+	php.writeFile(
+		`${options.documentRoot}/index.php`,
+		`<?php echo 'Hello wp-now!';`
+	);
+	php.writeFile(
+		'/internal/shared/ca-bundle.crt', rootCertificates.join('\n')
+	)
+}
+
+async function prepareWordPress( php: PHP, options: WPNowOptions 	) {
```
Comment (fluiddot) [inline vendor/wp-now/src/wp-now.ts]: Nitpick: there's a tab at the end of the argument list.
```suggestion
async function prepareWordPress( php: PHP, options: WPNowOptions ) {
```

File: vendor/wp-now/src/wp-now.ts [hunk 2]
```diff
@@ -158,6 +129,55 @@ export default async function startWPNow(
...
+	return { php, runtimeId: id };
+}
+
+function prepareDocumentRoot( php: PHP, options: WPNowOptions ) {
+	php.mkdir(options.documentRoot);
+	php.chdir(options.documentRoot);
+	php.writeFile(
+		`${options.documentRoot}/index.php`,
+		`<?php echo 'Hello wp-now!';`
+	);
```
Comment (fluiddot) [inline vendor/wp-now/src/wp-now.ts:152]: Unrelated to this PR but I wonder if this is really needed 🤔 .

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 ! Great work @jeroenpf 🏅  ! I've confirmed that after 400 requests, the PHP instance was rotated and kept working.

I added a couple of comments but none shouldn't block the PR.

File: vendor/wp-now/src/wp-now.ts (hunk 2 above)
Comment (jeroenpf) [reply vendor/wp-now/src/wp-now.ts:152]: I wasn't sure of the purpose so for now i left it. I think this whole file could use some refactoring as there is a lot of logic in there that does not apply to Studio. Its a bit difficult to know what is there for a reason and what is there because it was once copied from wp-now.

Comment (fluiddot) [reply vendor/wp-now/src/wp-now.ts:152]: Yeah, I agree. Let's keep it as-is for now.
