### PR TITLE
Output `.mjs` files when building CLI

### LINKED ISSUE #2941: WordPress Studio application is failing to start correctly after updating from version 1.7.6 to 1.7.7.
### Quick summary

The application is crashing because of a JavaScript configuration error. The internal command-line tool (CLI) used by Studio is trying to use modern JavaScript import syntax (import), but the Node.js runtime is treating the file as an older script type, resulting in the error:

SyntaxError: Cannot use import statement outside a module

This indicates that the update to version 1.7.7 was packaged incorrectly by the developers (missing a "type": "module" flag in a configuration file).

Error: ERR_MODULE_NOT_FOUND / SyntaxError: Cannot use import statement outside a module.
File: resources\cli\main.js.
Cause: The package.json associated with the CLI script is missing "type": "module", or the file extension should be .mjs. The Node.js version bundled with the app (v24.13.1) enforces strict module parsing, causing the application to crash on launch and site creation.

### Steps to reproduce

Update or install WordPress Studio to version 1.7.7 on Windows.
Launch the application (it may show a blank screen or empty site list).
Click on 'Add site' or attempt to create a new site.

### What you expected to happen

The application should start without errors, load the existing site list, and successfully create a new site when the button is clicked.

### What actually happened

The application fails to communicate with its internal CLI tool. Upon launch and any interaction (like creating a site), the process crashes with the error: SyntaxError: Cannot use import statement outside a module. The logs show the CLI file resources\cli\main.js is being loaded incorrectly, causing all site creation and loading functions to fail.

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform

Windows

### Logs or notes

[2026-03-28T19:56:08.877Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.6
[2026-03-28T19:56:11.834Z][info][main] Update available
[2026-03-28T19:56:11.835Z][info][main] Update available
[2026-03-28T19:57:28.484Z][info][main] [CLI - site ID 6febff2f-2cbd-4272-a327-ea68988b1c7f] {"name":"Twenty Twenty-Five","path":"\/wordpress\/wp-content\/themes\/twentytwentyfive","slug":"twentytwentyfive","isBlockTheme":true,"supportsWidgets":false,"supportsMenus":false}
[2026-03-28T19:57:50.422Z][info][main] Update has been downloaded
[2026-03-28T19:58:37.519Z][erro][main] Failed to kill child process with pid 6704. This likely means the process is already terminated. CLI args: [
  "_events"
]
[2026-03-28T19:58:37.522Z][info][main] Successfully killed child process with pid 102520. Args: [
  "wp",
  "--path",
  "C:\\Users\\Bit0071\\Studio\\yoel-02-wp-page-builder",
  "studio",
  "get-theme-details"
]
[2026-03-28T19:58:38.174Z][info][main] App is terminating[2026-03-28T19:58:39.671Z][info][main] Starting new session
[2026-03-28T19:58:39.672Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T19:58:39.771Z][info][main] App version: 1.7.7
[2026-03-28T19:58:39.772Z][info][main] Environment: production
[2026-03-28T19:58:39.772Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T19:58:39.772Z][info][main] Local timezone: America/New_York
[2026-03-28T19:58:39.772Z][info][main] App locale: en-US
[2026-03-28T19:58:39.772Z][info][main] System locale: en-US
[2026-03-28T19:58:39.772Z][info][main] Used language: en
[2026-03-28T19:58:39.791Z][info][main] Migrated auth/locale to C:\Users\[REDACTED]\.studio\shared.json
[2026-03-28T19:58:39.797Z][info][main] Migrated sites/snapshots to C:\Users\[REDACTED]\.studio\cli.json
[2026-03-28T19:58:39.801Z][info][main] Migrated Desktop settings from C:\Users\[REDACTED]\AppData\Roaming\Studio\appdata-v1.json to C:\Users\[REDACTED]\.studio\app.json
[2026-03-28T19:58:39.802Z][info][main] Migrated old appdata file from C:\Users\[REDACTED]\AppData\Roaming\Studio\appdata-v1.json to C:\Users\[REDACTED]\AppData\Roaming\Studio\appdata-v1.deprecated.json
[2026-03-28T19:58:39.805Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T19:58:39.931Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:76408) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T19:58:40.179Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T19:58:40.500Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:76288) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T19:59:03.076Z][info][main] App is terminating[2026-03-28T20:02:53.577Z][info][main] Starting new session
[2026-03-28T20:02:53.578Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T20:02:53.712Z][info][main] App version: 1.7.7
[2026-03-28T20:02:53.712Z][info][main] Environment: production
[2026-03-28T20:02:53.712Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T20:02:53.713Z][info][main] Local timezone: America/New_York
[2026-03-28T20:02:53.713Z][info][main] App locale: en-US
[2026-03-28T20:02:53.713Z][info][main] System locale: en-US
[2026-03-28T20:02:53.713Z][info][main] Used language: en
[2026-03-28T20:02:53.717Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T20:02:53.977Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:81992) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:02:54.238Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T20:02:54.557Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:14608) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:03:53.048Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:15792) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:03:53.050Z][erro][ren1] Failed to create site
[2026-03-28T20:04:11.639Z][info][main] Manually checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T20:05:28.475Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:53052) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:05:28.476Z][erro][ren1] Failed to create site
[2026-03-28T20:05:41.802Z][info][main] App is terminating[2026-03-28T20:50:13.268Z][info][main] Starting new session
[2026-03-28T20:50:13.270Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T20:50:13.456Z][info][main] App version: 1.7.7
[2026-03-28T20:50:13.457Z][info][main] Environment: production
[2026-03-28T20:50:13.457Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T20:50:13.457Z][info][main] Local timezone: America/New_York
[2026-03-28T20:50:13.457Z][info][main] App locale: en-US
[2026-03-28T20:50:13.457Z][info][main] System locale: en-US
[2026-03-28T20:50:13.457Z][info][main] Used language: en
[2026-03-28T20:50:13.464Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T20:50:13.591Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:21432) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:50:13.734Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T20:50:14.103Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:25320) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:50:56.643Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:14088) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:50:56.647Z][erro][ren1] Failed to create site
[2026-03-28T20:52:12.779Z][info][ren1] Token revoked
[2026-03-28T20:53:32.021Z][info][ren1] Token revoked
[2026-03-28T20:55:14.563Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:14932) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:55:14.566Z][erro][ren1] Failed to create site
[2026-03-28T20:55:49.155Z][info][main] App is terminating[2026-03-28T20:57:43.046Z][info][main] Starting new session
[2026-03-28T20:57:43.046Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T20:57:43.144Z][info][main] App version: 1.7.7
[2026-03-28T20:57:43.144Z][info][main] Environment: production
[2026-03-28T20:57:43.145Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T20:57:43.145Z][info][main] Local timezone: America/New_York
[2026-03-28T20:57:43.145Z][info][main] App locale: en-US
[2026-03-28T20:57:43.145Z][info][main] System locale: en-US
[2026-03-28T20:57:43.145Z][info][main] Used language: en
[2026-03-28T20:57:43.152Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T20:57:43.307Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:5464) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:57:43.433Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T20:57:43.834Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:11128) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T20:57:51.578Z][erro][main] Error: Command failed: 4294967295

    at ChildProcess.<anonymous> (node:electron/js2c/browser_init:2:11241)
    at ChildProcess.emit (node:events:520:35)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[2026-03-28T21:00:05.850Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:7796) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:00:05.852Z][erro][ren1] Failed to create site
[2026-03-28T21:02:07.085Z][info][main] App is terminating[2026-03-28T21:02:21.160Z][info][main] Starting new session
[2026-03-28T21:02:21.160Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:02:21.398Z][info][main] App version: 1.7.7
[2026-03-28T21:02:21.398Z][info][main] Environment: production
[2026-03-28T21:02:21.398Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:02:21.398Z][info][main] Local timezone: America/New_York
[2026-03-28T21:02:21.398Z][info][main] App locale: en-US
[2026-03-28T21:02:21.398Z][info][main] System locale: en-US
[2026-03-28T21:02:21.398Z][info][main] Used language: en
[2026-03-28T21:02:21.403Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:02:21.499Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:21004) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:02:21.628Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:02:21.988Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:15932) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:02:36.089Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:26068) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:02:36.092Z][erro][ren1] Failed to create site
[2026-03-28T21:02:52.659Z][info][main] App is terminating[2026-03-28T21:09:01.640Z][info][main] Starting new session
[2026-03-28T21:09:01.640Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:09:01.741Z][info][main] App version: 1.7.7
[2026-03-28T21:09:01.741Z][info][main] Environment: production
[2026-03-28T21:09:01.741Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:09:01.741Z][info][main] Local timezone: America/New_York
[2026-03-28T21:09:01.741Z][info][main] App locale: en-US
[2026-03-28T21:09:01.742Z][info][main] System locale: en-US
[2026-03-28T21:09:01.742Z][info][main] Used language: en
[2026-03-28T21:09:01.745Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:09:01.836Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:28024) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:09:01.965Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:09:02.313Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:27352) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:09:48.432Z][info][main] App is terminating[2026-03-28T21:16:30.265Z][info][main] Starting new session
[2026-03-28T21:16:30.266Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:16:30.362Z][info][main] App version: 1.7.7
[2026-03-28T21:16:30.362Z][info][main] Environment: production
[2026-03-28T21:16:30.362Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:16:30.363Z][info][main] Local timezone: America/New_York
[2026-03-28T21:16:30.363Z][info][main] App locale: en-US
[2026-03-28T21:16:30.363Z][info][main] System locale: en-US
[2026-03-28T21:16:30.363Z][info][main] Used language: en
[2026-03-28T21:16:30.368Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:16:30.496Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:29596) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:16:30.611Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:16:30.980Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:19504) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:16:51.282Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:28772) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:16:51.287Z][erro][ren1] Failed to create site
[2026-03-28T21:20:03.129Z][info][main] App is terminating[2026-03-28T21:21:27.898Z][info][main] Starting new session
[2026-03-28T21:21:27.898Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:21:28.000Z][info][main] App version: 1.7.7
[2026-03-28T21:21:28.000Z][info][main] Environment: production
[2026-03-28T21:21:28.000Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:21:28.000Z][info][main] Local timezone: America/New_York
[2026-03-28T21:21:28.000Z][info][main] App locale: en-US
[2026-03-28T21:21:28.000Z][info][main] System locale: en-US
[2026-03-28T21:21:28.000Z][info][main] Used language: en
[2026-03-28T21:21:28.005Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:21:28.166Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:29132) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:21:28.286Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:21:28.650Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:27968) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:21:34.034Z][info][main] App is terminating[2026-03-28T21:21:36.829Z][info][main] Starting new session
[2026-03-28T21:21:36.830Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:21:36.925Z][info][main] App version: 1.7.7
[2026-03-28T21:21:36.926Z][info][main] Environment: production
[2026-03-28T21:21:36.926Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:21:36.926Z][info][main] Local timezone: America/New_York
[2026-03-28T21:21:36.926Z][info][main] App locale: en-US
[2026-03-28T21:21:36.926Z][info][main] System locale: en-US
[2026-03-28T21:21:36.926Z][info][main] Used language: en
[2026-03-28T21:21:36.930Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:21:37.037Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:26332) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:21:37.155Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:21:37.512Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:7956) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:21:40.948Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:23992) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:21:40.951Z][erro][ren1] Failed to create site
[2026-03-28T21:35:16.844Z][info][main] Starting new session
[2026-03-28T21:35:16.845Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:35:16.942Z][info][main] App version: 1.7.7
[2026-03-28T21:35:16.942Z][info][main] Environment: production
[2026-03-28T21:35:16.942Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:35:16.942Z][info][main] Local timezone: America/New_York
[2026-03-28T21:35:16.942Z][info][main] App locale: en-US
[2026-03-28T21:35:16.942Z][info][main] System locale: en-US
[2026-03-28T21:35:16.942Z][info][main] Used language: en
[2026-03-28T21:35:16.946Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:35:17.082Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:27624) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:35:17.206Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:35:17.807Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:4500) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:35:26.011Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:27124) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:35:26.016Z][erro][ren1] Failed to create site
[2026-03-28T21:45:25.984Z][info][main] App is terminating[2026-03-28T21:45:34.610Z][info][main] Starting new session
[2026-03-28T21:45:34.611Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T21:45:34.712Z][info][main] App version: 1.7.7
[2026-03-28T21:45:34.713Z][info][main] Environment: production
[2026-03-28T21:45:34.713Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T21:45:34.713Z][info][main] Local timezone: America/New_York
[2026-03-28T21:45:34.713Z][info][main] App locale: en-US
[2026-03-28T21:45:34.713Z][info][main] System locale: en-US
[2026-03-28T21:45:34.713Z][info][main] Used language: en
[2026-03-28T21:45:34.716Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T21:45:34.807Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:28772) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:45:34.941Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T21:45:35.318Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:18440) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:45:43.035Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:27064) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T21:45:43.038Z][erro][ren1] Failed to create site
[2026-03-28T21:53:14.371Z][info][main] App is terminating[2026-03-28T22:07:57.901Z][info][main] Starting new session
[2026-03-28T22:07:57.901Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T22:07:58.000Z][info][main] App version: 1.7.7
[2026-03-28T22:07:58.000Z][info][main] Environment: production
[2026-03-28T22:07:58.001Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T22:07:58.001Z][info][main] Local timezone: America/New_York
[2026-03-28T22:07:58.001Z][info][main] App locale: en-US
[2026-03-28T22:07:58.001Z][info][main] System locale: en-US
[2026-03-28T22:07:58.001Z][info][main] Used language: en
[2026-03-28T22:07:58.004Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T22:07:58.111Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:28848) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:07:58.234Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T22:07:58.599Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:25188) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:08:00.930Z][erro][main] Error occurred in handler for 'createSite': CliCommandError: [Base message] Failed to create site
  [stderr] (node:6764) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:08:00.934Z][erro][ren1] Failed to create site
[2026-03-28T22:08:04.064Z][info][main] App is terminating[2026-03-28T22:17:11.808Z][info][main] Starting new session
[2026-03-28T22:17:11.809Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T22:17:11.910Z][info][main] App version: 1.7.7
[2026-03-28T22:17:11.910Z][info][main] Environment: production
[2026-03-28T22:17:11.911Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T22:17:11.911Z][info][main] Local timezone: America/New_York
[2026-03-28T22:17:11.911Z][info][main] App locale: en-US
[2026-03-28T22:17:11.911Z][info][main] System locale: en-US
[2026-03-28T22:17:11.911Z][info][main] Used language: en
[2026-03-28T22:17:11.915Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T22:17:12.083Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:27688) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:17:12.197Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T22:17:12.623Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:10916) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:17:37.435Z][info][main] App is terminating[2026-03-28T22:20:45.459Z][info][main] Starting new session
[2026-03-28T22:20:45.460Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=win32&studioArch=x64&version=1.7.7
[2026-03-28T22:20:45.557Z][info][main] App version: 1.7.7
[2026-03-28T22:20:45.557Z][info][main] Environment: production
[2026-03-28T22:20:45.557Z][info][main] Built from commit: 3b3f664df015797a8859f16a01d4e9009f160b07
[2026-03-28T22:20:45.557Z][info][main] Local timezone: America/New_York
[2026-03-28T22:20:45.557Z][info][main] App locale: en-US
[2026-03-28T22:20:45.557Z][info][main] System locale: en-US
[2026-03-28T22:20:45.557Z][info][main] Used language: en
[2026-03-28T22:20:45.561Z][info][main] Setting Sentry user ID: 305e6bf8-2492-4ab5-b844-f5a115a2ccf3
[2026-03-28T22:20:45.660Z][erro][main] Failed to fetch sites from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:21692) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1
[2026-03-28T22:20:45.782Z][warn][main] CLI events subscriber exited unexpectedly
[2026-03-28T22:20:46.154Z][erro][main] Failed to fetch snapshots from CLI: CliCommandError: [Base message] CLI command failed
  [stderr] (node:20716) Warning: Failed to load the ES module: C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Bit0071\AppData\Local\studio_app\app-1.7.7\resources\cli\main.js:1
import "node:path";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1735:18)
    at Module._compile (node:internal/modules/cjs/loader:1778:20)
    at Object..js (node:internal/modules/cjs/loader:1936:10)
    at Module.load (node:internal/modules/cjs/loader:1525:32)
    at Module._load (node:internal/modules/cjs/loader:1327:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.13.1
  [Exit code] 1

### PR DESCRIPTION
**Pull request by fredrikekelund**
## Related issues

- Fixes https://github.com/Automattic/studio/issues/2941

## How AI was used in this PR

For small directed tasks and for discussing Node's CJS/ESM loading behavior. 

## Proposed Changes

https://github.com/Automattic/studio/pull/2818 made Vite output ESM code in the CLI build, and updated `apps/cli/package.json` to contain a `type: module` field, which makes Node always interpret the code as ESM. However, this `package.json` file is not included in the CLI bundled with the app. 

Node.js follows this logic ([docs](https://nodejs.org/docs/latest-v24.x/api/esm.html#enabling)) when determining whether to interpret the code as CommonJS or ESM:

> Authors can tell Node.js to interpret JavaScript as an ES module via the .mjs file extension, the package.json "type" field with a value "module" […]
>
> Inversely, authors can explicitly tell Node.js to interpret JavaScript as CommonJS via the .cjs file extension, the package.json "type" field with a value "commonjs" […]
>
> When code lacks explicit markers for either module system, Node.js will inspect the source code of a module to look for ES module syntax. If such syntax is found, Node.js will run the code as an ES module; otherwise it will run the module as CommonJS. See Determining module system for more details.

In our testing, v1.7.7 of Studio and the CLI worked fine on Windows. That's because we didn't provide an explicit CJS/ESM signal to Node.js, so it inspected the source code to look for ES module syntax (which it found).

However, if a user places a `package.json` file in their home folder, that becomes the nearest `package.json` file for the CLI, which is the strongest signal to Node.js about which module system to use. I have reproduced this issue, and I suspect it's what caused the problem described in https://github.com/Automattic/studio/issues/2941.

This PR fixes the issue by outputting `.mjs` files in the CLI build. 

## Testing Instructions

1. Download and install the Windows dev build
2. In your Windows home directory, run `npm init -y`
3. Close Studio and open it again
4. Ensure that your site list loads as expected

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: apps/cli/package.json [hunk 1]
```diff
@@ -25,6 +24,7 @@
 	},
 	"dependencies": {
 		"@anthropic-ai/claude-agent-sdk": "^0.2.45",
+		"@inquirer/prompts": "^8.3.2",
```
Comment (fredrikekelund) [inline apps/cli/package.json:27]: This isn't related to the core change in this PR, but it's a CLI dependency and should be included here.

File: apps/cli/package.json [hunk 2]
```diff
@@ -7,11 +7,10 @@
 	"license": "GPL-2.0-or-later",
 	"type": "module",
 	"bin": {
-		"studio": "dist/cli/main.js"
+		"studio": "dist/cli/main.mjs"
 	},
 	"files": [
-		"dist/cli/*.js",
-		"dist/cli/wp-files/",
+		"dist/cli/",
```
Comment (fredrikekelund) [inline apps/cli/package.json:13]: Not related to the core change in this PR, but it simplifies publishing and has the same effect in practice (JS files and the `wp-files` directory are the only entries in `dist/cli`)

**Review by wojtekn — COMMENTED** [review]
The code change looks correct.

However, E2E tests and performance tests are failing. I couldn't start the site on my Windows machine when I used the built artifact.

When  I start in dev mode on Mac, I see an empty list of sites, and also the error related to daemon connection in the console.

**Review by wojtekn — APPROVED** [review]
It works well now on Windows according to the instructions.
