### PR TITLE
Studio: Handle Add Site top bar menu item in onboarding screen

### LINKED ISSUE #377: The "Add site" action doesn't work if there is no site
### Quick summary

The "Add site" action doesn't work if there is no site.

https://github.com/user-attachments/assets/7b5407c1-f0ef-40ad-8d29-6394175cf2fb

### Steps to reproduce

- Delete all sites.
- From the app menu, access File > Add site.

### What you expected to happen

The "Add site" modal should open.

### What actually happened

Nothing happen.

### Impact

One

### Available workarounds?

No but the app is still usable

### Platform

Windows

### Logs or notes

Studio version: 1.0.6
OS: Windows 11

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes https://github.com/Automattic/studio/issues/377

## Proposed Changes

This PR changes the behaviour of the `Add site` menu item in the top bar menu when the user is presented with the onboarding screen. Instead of doing nothing, the menu item now triggers the site creation.

## Testing Instructions

* Pull the changes from this branch
* Start the app with `npm start`
* Delete all local sites to be presented with the onboarding screen
* Once on onboarding screen, click on `Add Site..` in the top bar menu
* Observe that it creates a new site and you are presented with the loading screen
* Observe that once the site is created and you try to click on `Add Site...`, it opens a modal with add site form

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/components/onboarding.tsx [hunk 1]
```diff
@@ -52,6 +57,12 @@ export default function Onboarding() {
 		fileForImport,
 	} = useAddSite();
 	const [ fileError, setFileError ] = useState( '' );
+	const { importState } = useImportExport();
+	const { data } = useSiteDetails();
+
+	const isAnySiteProcessing = data.some(
+		( site ) => site.isAddingSite || importState[ site.id ]?.isNewSite
+	);
```
Comment (katinthehatsite) [inline src/components/onboarding.tsx:65]: We use this logic in a couple of places so we could probably move it into a separate hook. Happy to create a follow -up PR!

File: src/components/onboarding.tsx [hunk 2]
```diff
@@ -141,7 +159,7 @@ export default function Onboarding() {
 							onSelectPath={ handlePathSelectorClick }
 							error={ error }
 							doesPathContainWordPress={ doesPathContainWordPress }
-							onSubmit={ handleSubmit }
+							onSubmit={ preventEventAndHandleSubmit }
```
Comment (kozer) [inline src/components/onboarding.tsx]:
```suggestion
							onSubmit={ ( event: FormEvent ) => {
										event.preventDefault();
										await onAddSite();
							} }
```

What about this one, remove ` preventEventAndHandleSubmit`, and rename `handleSubmit` to `onAddSite`?

What do you think about that change?

**Comment by kozer** [comment]
@katinthehatsite , I left a comment.
Other than that, it works as expected! Nice work!

File: src/components/onboarding.tsx (hunk 2 above)
Comment (katinthehatsite) [reply src/components/onboarding.tsx]: Sounds good to me! I added this logic in https://github.com/Automattic/studio/pull/492/commits/424cb682adaa733e9e2cad5056af6aa6553f7f7a

**Review by kozer — APPROVED** [review]
Tested it, and works as expected! Nice work @katinthehatsite !
