### PR TITLE
Studio: fix setting menu not open if no sites

### LINKED ISSUE #241: If there is no site, the Settings menu will not open.
### Quick summary

If there is no site, the Settings menu will not open.

https://github.com/Automattic/studio/assets/54422211/f8b48823-7b0a-47c4-aa6d-398620bc464a

### Steps to reproduce

- If sites exist, delete them all.
- Click "Studio" > "Settings" from the app menu.

### What you expected to happen

Nothing happens.

### What actually happened

I would like to either:

- The Settings menu should open the modal correctly even if the site doesn't exist.
- If the site doesn't exist, the Settings menu shouldn't be displayed.

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Windows

### Logs or notes

OS: Windows 11
Studio version: 1.0.3

### PR DESCRIPTION
**Pull request by kozer**
Fixes https://github.com/Automattic/studio/issues/241

## Proposed Changes

This PR fixes a bug,  where when the user clicks the "Settings" menu item from the onboarding screen, the menu doesn't open.

## Testing Instructions
- If sites exist, delete them all ( or make a backup in a different folder )
- In the onboarding session, click "Studio" > "Settings" from the app menu.
- Ensure that the settings menu, appears

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/components/app.tsx [hunk 1]
```diff
@@ -45,6 +46,7 @@ export default function App() {
 				>
 					<SiteContentTabs />
 				</main>
+				<UserSettings />
```
Comment (fluiddot) [inline src/components/app.tsx]: I can't open the settings window while on the onboarding screen. I think we need to render this component also in line 26.

Comment (kozer) [reply src/components/app.tsx]: Yeah, my bad! I had it there originally, and then removed it accidentally. Thanks!

**Review by wojtekn — APPROVED** [review]
The code change looks clear. It fixes the issue for me.
