### PR TITLE
Studio: The "Add site" action doesn't work if there is no site

### LINKED ISSUE #377: The "Add site" action doesn't work if there is no site
### Quick summary

The "Add site" action doesn't work if there is no site.

https://github.com/user-attachments/assets/7b5407c1-f0ef-40ad-8d29-6394175cf2fb

### Steps to reproduce

- Delete all sites.
- From the app menu, access File > Add site.

### What you expected to happen

The "Add site" modal should open.

### What actually happened

Nothing happen.

### Impact

One

### Available workarounds?

No but the app is still usable

### Platform

Windows

### Logs or notes

Studio version: 1.0.6
OS: Windows 11

### PR DESCRIPTION
**Pull request by katinthehatsite**
Closes https://github.com/Automattic/studio/issues/377

## Proposed Changes

This PR does the following:

* when the user has no sites, is on onboarding screen and they click on `File > Add site` in the topbar menu, the menu option is disabled
* when the user has some sites and they click on `File > Add site` in the topbar menu, that menu option is enabled ,and they can open the modal for adding a site

It addresses the current issue when the `File > Add site` looks enabled when the user has no sites and is on onboarding screen but clicking on it does nothing.

## Testing Instructions

* Pull the changes from this branch
* Start the app with `nvm use && npm install && npm start`
* Delete all sites and ensure that you see the onboarding screen
* Click on `File > Add site` option in the topbar menu
* Observe that that menu is disabled
* Create a site through onboarding screen so that you have at least one site
* Click on `File > Add site` option in the topbar menu
* Observe that `Add site` menu item is enabled
* Confirm that you can click it and it opens the modal to add a new site

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/hooks/use-i18n-data.tsx [hunk 1]
```diff
@@ -19,26 +20,30 @@ export const I18nDataProvider = ( { children }: { children: React.ReactNode } )
...
+				defaultI18n.setLocaleData( translations );
+				getIpcApi().setDefaultLocaleData( translations );
+			} else {
+				// In case we don't find translations, we reset the locale data to
+				// fallback to the default translations.
+				defaultI18n.resetLocaleData();
+				getIpcApi().resetDefaultLocaleData();
+			}
+			// App menu is reloaded to ensure the items show the translated strings.
+			getIpcApi().setupAppMenu( { needsOnboarding } );
```
Comment (fluiddot) [inline src/hooks/use-i18n-data.tsx:43]: I wouldn't expect that refreshing the app menu requires passing the entire config parameters, like `needsOnboarding`. That said, I wonder if we could create a React context to manage the app menu from a global perspective instead.

The provider will use the hook `useOnboarding` to retrieve `needsOnboarding`, and set a side effect to update that app menu as we do in:
https://github.com/Automattic/studio/blob/c444a1c2c1c205ae98bb8e3968a40dd11fab3372/src/components/app.tsx#L24-L26

Additionally, the provider will expose a function to refresh the app menu that will be consumed here. We could also expose other functions in the future to make updates in the app bar in a reactive way.

With the above approach, we'll unlock updating the app menu from anywhere on the app. WDYT?

File: src/components/onboarding.tsx [hunk 2]
```diff
@@ -125,13 +117,6 @@ export default function Onboarding() {
 		[ setFileForImport ]
 	);
 
-	useIpcListener( 'add-site', () => {
-		if ( isAnySiteProcessing || ! needsOnboarding ) {
-			return;
-		}
-		onAddSite();
-	} );
```
Comment (fluiddot) [inline src/components/onboarding.tsx:133]: I assume that we no longer need this because the `Add site` menu item will be disabled. Is this accurate?

**Review by wojtekn — APPROVED** [review]
Feature-wise works as expected, thanks!

File: src/hooks/use-i18n-data.tsx (hunk 1 above)
Comment (sejas) [reply src/hooks/use-i18n-data.tsx:43]: Maybe another alternative would be reading the number of sites directly on IPC?

Something like (I didn't try the code):
```
export async function setupAppMenu( _event: IpcMainInvokeEvent ) {
	const userData = await loadUserData();
	const needsOnboarding = userData.sites.length === 0;
	setupMenu( { needsOnboarding } );
}
```

**Review by sejas — APPROVED** [review]
It works as expected. I see the add site menu item is disabled for onboarding, and enabled when we have one site or more.
Changing the language respects the correct state.

Screenshot 2024-10-01 at 15 36 34

**Comment by katinthehatsite** [comment]
Thanks @sejas - that is what I was planning to do initially (meaning reading the amount of sites) but I found that it works similarly 👍

File: src/components/onboarding.tsx (hunk 2 above)
Comment (katinthehatsite) [reply src/components/onboarding.tsx:133]: Yeah we initially added in https://github.com/Automattic/studio/pull/492/files when we were trying to make that menu item submit the form to add a site instead of being disabled when the user needs onboarding but it is no longer necessary (as we decided to remove this behavior).

File: src/hooks/use-i18n-data.tsx (hunk 1 above)
Comment (katinthehatsite) [reply src/hooks/use-i18n-data.tsx:43]: Since we need to manipulate just one menu item for now, I am going to merge this as this will have an immediate positive effect on the user experience. Let's open a separate issue to create a React context and make this more adaptable for future implementations.

Comment (katinthehatsite) [reply src/hooks/use-i18n-data.tsx:43]: I created the issue related to this here: https://github.com/Automattic/dotcom-forge/issues/9313
