### PR TITLE
Fix: Prevent server process from hanging during stop operation

### LINKED ISSUE #985: Site not stopping
### Quick summary

When stopping a site, I've had constant issues with it remaining in a "Stopping..." state after breaking something on the site. 
In this case, I was configuring a plugin - the site stopped resolving, so I wanted to restart (or stop, start) the site. 
The "Stopping..." dialogue hangs there without further information displaced. 

The error logs show the following: 

```

[2025-02-26T16:03:22.714Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T16:03:22.893Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T16:03:22.894Z][info][site-server-process] mode: wordpress
[2025-02-26T16:03:22.894Z][info][site-server-process] php: 8.2
[2025-02-26T16:03:22.894Z][info][site-server-process] wp: latest
[2025-02-26T16:03:22.894Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T16:03:22.894Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T16:03:24.195Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T16:03:25.652Z][info][main] Server started for 'MSD Demo'
[2025-02-26T16:07:43.171Z][warn][site-server-process] PHP.run() output was: 
[2025-02-26T16:07:43.172Z][erro][site-server-process] Error: PHP.run() failed with exit code 255 and the following output: 
    at PHP.run (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1581199)
    at async PHPRequestHandler.ce (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1600691)
    at async PHPRequestHandler.le (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1600356)
[2025-02-26T16:12:10.618Z][erro][site-server-process] {}
[2025-02-26T16:13:35.653Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:13:48.458Z][info][main] Stopping server with ID 4c204f8a-f0ad-432d-974e-4f791ba210db
[2025-02-26T16:13:48.460Z][info][site-server-process] Server stopped

```

The last 4 log entries show that one site stopped fine (ID 4c204f8a-f0ad-432d-974e-4f791ba210db). The second site " ID 8a0a68a6-214e-4a06-87e4-426b54e9c476" remains in a hung state until I force quit WordPress Studio. 
Upon restart, I can start the site again and it'll work without issue. 

### Steps to reproduce

1. Setup default WordPress site. 
2. Install Remote Data Blocks Plugin.
3. Setup third party data ingestion via Google Sheets (https://github.com/Automattic/remote-data-blocks/blob/trunk/docs/tutorials/google-sheets.md). 
4. When the site eventually fails (This site can’t be reached - localhost refused to connect.). Attempt to stop the site. 

### What you expected to happen

The site/container to force quit after X seconds if a graceful stop can't be complete. 

### What actually happened

It hangs on "Stopping..." indefinitely. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform

Mac Silicon

### Logs or notes

Studio log - "MSD Demo" is the site with the issue: 

```

[2025-02-26T00:35:49.275Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T01:38:31.563Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T03:04:52.883Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T04:25:05.774Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T05:41:39.508Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T07:00:09.025Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T08:29:01.532Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T09:31:40.898Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T09:44:04.785Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T09:44:04.998Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T09:44:04.999Z][info][site-server-process] mode: wordpress
[2025-02-26T09:44:04.999Z][info][site-server-process] php: 8.2
[2025-02-26T09:44:04.999Z][info][site-server-process] wp: latest
[2025-02-26T09:44:04.999Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T09:44:04.999Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T09:44:06.366Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T09:44:08.042Z][info][main] Server started for 'MSD Demo'
[2025-02-26T10:00:42.334Z][erro][site-server-process] {}
[2025-02-26T10:02:22.597Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T10:02:26.310Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T10:02:27.660Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T10:06:45.950Z][erro][main] Error occurred in handler for 'getThemeDetails': TypeError: Object has been destroyed
    at n.fromWebContents (node:electron/js2c/browser_init:2:14314)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2426935
    at Generator.next (<anonymous>)
    at o (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2410880)
[2025-02-26T10:07:40.816Z][erro][main] Error occurred in handler for 'getThemeDetails': TypeError: Object has been destroyed
    at n.fromWebContents (node:electron/js2c/browser_init:2:14314)
    at /Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2426935
    at Generator.next (<anonymous>)
    at o (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2410880)
[2025-02-26T10:12:35.989Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T10:12:47.106Z][info][main] App is terminating[2025-02-26T10:12:56.762Z][info][main] Starting new session
[2025-02-26T10:12:56.766Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T10:12:56.919Z][info][main] App version: 1.3.4
[2025-02-26T10:12:56.919Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T10:12:56.925Z][info][main] Local timezone: Europe/London
[2025-02-26T10:12:56.925Z][info][main] App locale: en-GB
[2025-02-26T10:12:56.925Z][info][main] System locale: en-GB
[2025-02-26T10:12:56.925Z][info][main] Used language: en
[2025-02-26T10:12:56.934Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T10:12:57.458Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T10:12:57.847Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T10:12:58.799Z][info][main] Stopped watching for file changes
[2025-02-26T10:12:59.234Z][info][main] SQLite Command is up to date.
[2025-02-26T10:12:59.264Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T10:12:59.453Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T10:12:59.453Z][info][site-server-process] mode: wordpress
[2025-02-26T10:12:59.453Z][info][site-server-process] php: 8.2
[2025-02-26T10:12:59.453Z][info][site-server-process] wp: latest
[2025-02-26T10:12:59.454Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T10:12:59.454Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T10:13:00.676Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T10:13:02.241Z][info][main] Server started for 'MSD Demo'
[2025-02-26T10:13:34.094Z][erro][site-server-process] {}
[2025-02-26T10:14:09.341Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T10:15:01.487Z][info][main] App is terminating[2025-02-26T10:54:27.880Z][info][main] Starting new session
[2025-02-26T10:54:27.886Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T10:54:28.092Z][info][main] App version: 1.3.4
[2025-02-26T10:54:28.093Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T10:54:28.098Z][info][main] Local timezone: Europe/London
[2025-02-26T10:54:28.098Z][info][main] App locale: en-GB
[2025-02-26T10:54:28.098Z][info][main] System locale: en-GB
[2025-02-26T10:54:28.098Z][info][main] Used language: en
[2025-02-26T10:54:28.108Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T10:54:28.672Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T10:54:29.070Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T10:54:29.957Z][info][main] Stopped watching for file changes
[2025-02-26T10:54:30.384Z][info][main] SQLite Command is up to date.
[2025-02-26T10:54:30.670Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T10:54:30.866Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T10:54:30.867Z][info][site-server-process] mode: wordpress
[2025-02-26T10:54:30.867Z][info][site-server-process] php: 8.2
[2025-02-26T10:54:30.867Z][info][site-server-process] wp: latest
[2025-02-26T10:54:30.867Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T10:54:30.868Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T10:54:32.233Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T10:54:33.814Z][info][main] Server started for 'MSD Demo'
[2025-02-26T11:04:33.809Z][erro][site-server-process] {}
[2025-02-26T11:04:46.750Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T11:11:06.820Z][info][main] App is terminating[2025-02-26T11:11:08.087Z][info][main] Starting new session
[2025-02-26T11:11:08.090Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T11:11:08.205Z][info][main] App version: 1.3.4
[2025-02-26T11:11:08.206Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T11:11:08.211Z][info][main] Local timezone: Europe/London
[2025-02-26T11:11:08.211Z][info][main] App locale: en-GB
[2025-02-26T11:11:08.211Z][info][main] System locale: en-GB
[2025-02-26T11:11:08.211Z][info][main] Used language: en
[2025-02-26T11:11:08.218Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T11:11:08.976Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T11:11:09.357Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T11:11:10.238Z][info][main] Stopped watching for file changes
[2025-02-26T11:11:10.720Z][info][main] SQLite Command is up to date.
[2025-02-26T11:11:11.757Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T11:11:11.950Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T11:11:11.951Z][info][site-server-process] mode: wordpress
[2025-02-26T11:11:11.951Z][info][site-server-process] php: 8.2
[2025-02-26T11:11:11.951Z][info][site-server-process] wp: latest
[2025-02-26T11:11:11.951Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T11:11:11.951Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T11:11:13.198Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T11:11:14.726Z][info][main] Server started for 'MSD Demo'
[2025-02-26T11:11:42.391Z][erro][site-server-process] {}
[2025-02-26T11:13:51.188Z][info][main] App is terminating[2025-02-26T11:42:54.294Z][info][main] Starting new session
[2025-02-26T11:42:54.300Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T11:42:54.514Z][info][main] App version: 1.3.4
[2025-02-26T11:42:54.514Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T11:42:54.520Z][info][main] Local timezone: Europe/London
[2025-02-26T11:42:54.520Z][info][main] App locale: en-GB
[2025-02-26T11:42:54.520Z][info][main] System locale: en-GB
[2025-02-26T11:42:54.520Z][info][main] Used language: en
[2025-02-26T11:42:54.530Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T11:42:55.067Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T11:42:55.467Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T11:42:56.345Z][info][main] Stopped watching for file changes
[2025-02-26T11:42:56.779Z][info][main] SQLite Command is up to date.
[2025-02-26T11:42:57.085Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T11:42:57.269Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T11:42:57.269Z][info][site-server-process] mode: wordpress
[2025-02-26T11:42:57.269Z][info][site-server-process] php: 8.2
[2025-02-26T11:42:57.269Z][info][site-server-process] wp: latest
[2025-02-26T11:42:57.269Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T11:42:57.269Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T11:42:58.929Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T11:43:00.453Z][info][main] Server started for 'MSD Demo'
[2025-02-26T11:45:54.704Z][erro][site-server-process] {}
[2025-02-26T11:52:19.352Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T12:42:54.919Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T13:42:55.306Z][info][main] Automatically checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T14:15:14.450Z][info][main] App is terminating[2025-02-26T15:44:38.145Z][info][main] Starting new session
[2025-02-26T15:44:38.151Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T15:44:38.253Z][info][main] App version: 1.3.4
[2025-02-26T15:44:38.253Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T15:44:38.258Z][info][main] Local timezone: Europe/London
[2025-02-26T15:44:38.258Z][info][main] App locale: en-GB
[2025-02-26T15:44:38.258Z][info][main] System locale: en-GB
[2025-02-26T15:44:38.258Z][info][main] Used language: en
[2025-02-26T15:44:38.281Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T15:44:38.974Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T15:44:39.358Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T15:44:40.213Z][info][main] Stopped watching for file changes
[2025-02-26T15:44:40.640Z][info][main] SQLite Command is up to date.
[2025-02-26T15:47:14.282Z][info][main] App is terminating[2025-02-26T15:47:17.021Z][info][main] Starting new session
[2025-02-26T15:47:17.024Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T15:47:17.107Z][info][main] App version: 1.3.4
[2025-02-26T15:47:17.107Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T15:47:17.108Z][info][main] Local timezone: Europe/London
[2025-02-26T15:47:17.108Z][info][main] App locale: en-GB
[2025-02-26T15:47:17.108Z][info][main] System locale: en-GB
[2025-02-26T15:47:17.108Z][info][main] Used language: en
[2025-02-26T15:47:17.114Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T15:47:17.624Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T15:47:18.006Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T15:47:18.710Z][info][main] Stopped watching for file changes
[2025-02-26T15:47:19.109Z][info][main] SQLite Command is up to date.
[2025-02-26T15:47:19.842Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T15:47:20.014Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T15:47:20.014Z][info][site-server-process] mode: wordpress
[2025-02-26T15:47:20.015Z][info][site-server-process] php: 8.2
[2025-02-26T15:47:20.015Z][info][site-server-process] wp: latest
[2025-02-26T15:47:20.015Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T15:47:20.015Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T15:47:22.386Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T15:47:23.921Z][info][main] Server started for 'MSD Demo'
[2025-02-26T15:47:28.793Z][erro][site-server-process] {}
[2025-02-26T15:48:55.211Z][info][wp-cli-process] Stopped watching for file changes
[2025-02-26T15:48:57.413Z][info][wp-cli-process] Stopped watching for file changes
[2025-02-26T15:50:03.029Z][info][wp-cli-process] Stopped watching for file changes
[2025-02-26T15:50:24.385Z][info][wp-cli-process] Stopped watching for file changes
[2025-02-26T15:50:26.002Z][info][wp-cli-process] Stopped watching for file changes
[2025-02-26T15:51:14.401Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T15:53:48.592Z][info][main] Manually checking for update: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T15:58:45.070Z][info][main] App is terminating
[2025-02-26T15:59:20.133Z][info][main] Starting new session
[2025-02-26T15:59:20.136Z][info][main] Checking for update on app launch: https://public-api.wordpress.com/wpcom/v2/studio-app/updates?platform=darwin&arch=arm64&version=1.3.4
[2025-02-26T15:59:20.215Z][info][main] App version: 1.3.4
[2025-02-26T15:59:20.215Z][info][main] Built from commit: 66cc039ee43d041e976170f580480e726e65bbea
[2025-02-26T15:59:20.216Z][info][main] Local timezone: Europe/London
[2025-02-26T15:59:20.216Z][info][main] App locale: en-GB
[2025-02-26T15:59:20.216Z][info][main] System locale: en-GB
[2025-02-26T15:59:20.216Z][info][main] Used language: en
[2025-02-26T15:59:20.222Z][info][main] Setting Sentry user ID: 206006b6-d5dd-48a1-b3bc-3cefe0c4e56b
[2025-02-26T15:59:20.733Z][info][main] WordPress latest folder already exists. Skipping download.
[2025-02-26T15:59:21.124Z][info][main] SQLite folder already exists. Skipping download.
[2025-02-26T15:59:21.844Z][info][main] Stopped watching for file changes
[2025-02-26T15:59:22.259Z][info][main] SQLite Command is up to date.
[2025-02-26T15:59:33.568Z][info][main] Starting server for 'Bleeding edge'
[2025-02-26T15:59:33.739Z][info][site-server-process] directory: /Users/ppolo99/Studio/bleeding-edge
[2025-02-26T15:59:33.740Z][info][site-server-process] mode: wordpress
[2025-02-26T15:59:33.740Z][info][site-server-process] php: 8.2
[2025-02-26T15:59:33.740Z][info][site-server-process] wp: latest
[2025-02-26T15:59:33.740Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T15:59:33.740Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T15:59:36.474Z][info][site-server-process] Server running at http://localhost:8883
[2025-02-26T15:59:37.966Z][info][main] Server started for 'Bleeding edge'
[2025-02-26T16:03:22.714Z][info][main] Starting server for 'MSD Demo'
[2025-02-26T16:03:22.893Z][info][site-server-process] directory: /Users/ppolo99/Studio/msd-demo
[2025-02-26T16:03:22.894Z][info][site-server-process] mode: wordpress
[2025-02-26T16:03:22.894Z][info][site-server-process] php: 8.2
[2025-02-26T16:03:22.894Z][info][site-server-process] wp: latest
[2025-02-26T16:03:22.894Z][info][site-server-process] WordPress latest folder already exists. Skipping download.
[2025-02-26T16:03:22.894Z][info][site-server-process] SQLite folder already exists. Skipping download.
[2025-02-26T16:03:24.195Z][info][site-server-process] Server running at http://localhost:8881
[2025-02-26T16:03:25.652Z][info][main] Server started for 'MSD Demo'
[2025-02-26T16:07:43.171Z][warn][site-server-process] PHP.run() output was: 
[2025-02-26T16:07:43.172Z][erro][site-server-process] Error: PHP.run() failed with exit code 255 and the following output: 
    at PHP.run (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1581199)
    at async PHPRequestHandler.ce (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1600691)
    at async PHPRequestHandler.le (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/siteServerProcess.js:2:1600356)
[2025-02-26T16:12:10.618Z][erro][site-server-process] {}
[2025-02-26T16:13:35.653Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:13:48.458Z][info][main] Stopping server with ID 4c204f8a-f0ad-432d-974e-4f791ba210db
[2025-02-26T16:13:48.460Z][info][site-server-process] Server stopped

```

Quitting the app will give the final log: 

```

[2025-02-26T16:25:38.062Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:25:39.015Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:25:39.153Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:25:39.319Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:25:39.479Z][info][main] Stopping server with ID 8a0a68a6-214e-4a06-87e4-426b54e9c476
[2025-02-26T16:25:45.727Z][info][main] App is terminating

```

### PR DESCRIPTION
**Pull request by bcotrim**
## Related issues

- Fixes #985

## Proposed Changes

- Added isResolved flag to prevent multiple promise resolutions in the #killProcess method
- Added force kill with SIGKILL if graceful shutdown fails
- Improved process cleanup by clearing timeouts and handling process state properly

## Testing Instructions

Follow the steps mentioned in the issue
- Setup default WordPress site.
- Install Remote Data Blocks Plugin.
- Setup third party data ingestion via Google Sheets (https://github.com/Automattic/remote-data-blocks/blob/trunk/docs/tutorials/google-sheets.md).
- When the site eventually fails (This site can’t be reached - localhost refused to connect.). Attempt to stop the site.
- The site stops after the timeout timer runs out, instead of hanging.
- Confirm that there are no pending processes for that site

More details on reproducing the issue (thanks @ppolo99): p1741865890679379/1741864717.468099-slack-C04GESRBWKW

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/lib/site-server-process.ts [hunk 1]
```diff
@@ -142,12 +142,33 @@ export default class SiteServerProcess {
...
+
+				// Check if process and pid are still valid before attempting force kill
+				if ( process && process.pid ) {
+					require( 'process' ).kill( process.pid, 'SIGKILL' );
+				} else {
+					if ( ! isResolved ) {
+						isResolved = true;
+						resolve();
+					}
+				}
```
Comment (fredrikekelund) [inline src/lib/site-server-process.ts]:
```suggestion
				if ( process.pid ) {
					kill( process.pid, 'SIGKILL' );
				} else {
					isResolved = true;
					resolve();
				}
```
Nit, but we already know that `process` is defined at this point, and we also know that `isResolved` is false because this callback returns early if that's the case.

I also don't see a good reason to use the `require` pattern here – we might as well do `import { kill } from 'process';`

File: src/lib/site-server-process.ts [hunk 2]
```diff
@@ -142,12 +142,33 @@ export default class SiteServerProcess {
...
+					isResolved = true;
+					if ( code !== 0 ) {
+						reject( new Error( `Site server process exited with code ${ code } upon stopping` ) );
+					} else {
+						resolve();
+					}
 				}
-				resolve();
 			} );
 			process.kill();
```
Comment (fredrikekelund) [inline src/lib/site-server-process.ts]: `process.kil()` returns a boolean per the [Electron docs](https://www.electronjs.org/docs/latest/api/utility-process). Is that a useful signal for us maybe..?

**Review by fredrikekelund — APPROVED** [review]
Does what it says on the tin 👍 

I'll create a separate issue for investigating why the Remote Data Blocks plugin throws an error like this, but this is still a great improvement.

File: src/lib/site-server-process.ts (hunk 2 above)
Comment (bcotrim) [reply src/lib/site-server-process.ts]: That's a nice catch!
I've made some adjustments to use the return value from `process.kill()` instead of the TIMEOUT.
Could you take another look, please? 🙏

**Review by wojtekn — APPROVED** [review]
Looks good @bcotrim .

Could you please update description to account for the timeout removal?

File: src/lib/site-server-process.ts [hunk 3]
```diff
@@ -142,14 +143,26 @@ export default class SiteServerProcess {
...
+						reject( new Error( `Site server process exited with code ${ code } upon stopping` ) );
+					} else {
+						resolve();
+					}
 				}
-				resolve();
 			} );
-			process.kill();
+			// process.kill() returns false if we're not able to kill the process.
+			if ( ! process.kill() && ! isResolved ) {
```
Comment (fredrikekelund) [inline src/lib/site-server-process.ts]:
```suggestion
			if ( ! process.kill() ) {
```
I can't really imagine a scenario in which `isResolved` would be true at this point 🤔

File: src/lib/site-server-process.ts [hunk 4]
```diff
@@ -142,14 +143,26 @@ export default class SiteServerProcess {
 		}
 
 		return new Promise< void >( ( resolve, reject ) => {
+			let isResolved = false;
 			process.once( 'exit', ( code ) => {
-				if ( code !== 0 ) {
-					reject( new Error( `Site server process exited with code ${ code } upon stopping` ) );
-					return;
+				if ( ! isResolved ) {
+					isResolved = true;
```
Comment (fredrikekelund) [inline src/lib/site-server-process.ts]:
```suggestion
```
Nit, but given that we're only listening to the `exit` event once, do we really need to modify `isResolved` here?

**Review by fredrikekelund — APPROVED** [review]
Nice 👍 New solution also works as expected.

File: src/lib/site-server-process.ts (hunk 3 above)
Comment (bcotrim) [reply src/lib/site-server-process.ts]: I guess I was being extra careful with that condition, but it doesn't make sense anymore with the new approach.
I have removed `isResolved` check and works as expected.
Thanks for the feedback!
