### PR TITLE
Unify Import labels and mention another supported formats

### LINKED ISSUE #783: Import a backup option is unclear and doesn't seem to work
### Quick summary

When creating a new site in Studio, there is an optional step to import a back up.

The text reads `Jetpack and WordPress backups supported` which led me to believe that I could use a `.xml` or an `sql` export from an existing site but this didn't work. Additionally, the learn more link takes the user to a page that has no references to import/export.

Moving users from a non DotCom environment to Studio will be much easier if these options are supported.

## Screen recording
https://github.com/user-attachments/assets/2862d745-8884-4e0c-b4b8-38c61e9b3682

Once I created the site, I was able to use the Import/Export panel to import using an `sql` file.

### Steps to reproduce

1. Start Studio
2. Create a new site
3. Try to use an XML or SQL export for the import step

### What you expected to happen

Based on the statement `WordPress backups`, I would have expected to be able to use either an XML or SQL file.

### What actually happened

It didn't work and I don't have a Jetpack backup to use.

### Impact

One

### Available workarounds?

Yes. The import can happen after creating the site.

### Platform

Mac Silicon

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
## Related issues

- Fixes https://github.com/Automattic/studio/issues/783

## Proposed Changes

The import field label currently reads `Jetpack and WordPress backups supported` and seems confusing.

I propose to unify the wording used in labels in the 'Add site' form and 'Import / Export' tabs and mention that other formats than Jetback backup are supported.

Screenshot 2025-01-08 at 09 00 08

Screenshot 2025-01-08 at 08 59 55

## Testing Instructions

1. Open 'Add site' form and confirm that the import label is clear
2. Add the site
3. Open 'Import / Export' tab and confirm that the import label is clear

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/components/site-form.tsx [hunk 1]
```diff
@@ -259,7 +259,9 @@ export const SiteForm = ( {
 							</label>
 							<span className="text-a8c-gray-50 text-xs">
 								{ createInterpolateElement(
-									__( 'Jetpack and WordPress backups supported. <button>Learn more</button>' ),
+									__(
+										'Import a Jetpack backup or another full-site backup format. <button>Learn more</button>'
```
Comment (ivan-ottinger) [inline src/components/site-form.tsx]:
```suggestion
										'Import a Jetpack backup or a full-site backup in another format. <button>Learn more</button>'
```

File: src/components/content-tab-import-export.tsx [hunk 2]
```diff
@@ -225,7 +225,9 @@ const ImportSite = ( {
 			<div className="a8c-subtitle-small mb-1">{ __( 'Import' ) }</div>
 			<div className="text-a8c-gray-70 a8c-body mb-4">
 				{ createInterpolateElement(
-					__( 'Import a Jetpack backup or a .sql database file. <button>Learn more</button>' ),
+					__(
+						'Import a Jetpack backup, another full-site backup, or a .sql database file. <button>Learn more</button>'
```
Comment (ivan-ottinger) [inline src/components/content-tab-import-export.tsx]:
```suggestion
						'Import a Jetpack backup, a full-site backup in another format, or a .sql database file. <button>Learn more</button>'
```

**Review by ivan-ottinger — APPROVED** [review]
The proposed copy is much more clear now. 👌🏼 

I just proposed two slight adjustments we could consider (please see the inline comments).

File: src/components/content-tab-import-export.tsx (hunk 2 above)
Comment (katinthehatsite) [reply src/components/content-tab-import-export.tsx]: Alternatively, we can also do something like:


```suggestion
						'Import a Jetpack backup, a full-site backup from another tool or service, or a .sql database file.. <button>Learn more</button>'
```

File: src/components/site-form.tsx (hunk 1 above)
Comment (katinthehatsite) [reply src/components/site-form.tsx]:
```suggestion
						'Import a Jetpack backup or a full-site backup from another tool or service. <button>Learn more</button>'
```

Comment (wojtekn) [reply src/components/site-form.tsx]: Thanks for your proposals. I updated the text and it looks easier to read now. I chose the shorter version as that way, it still fits into one line in most window sizes.

**Review by katinthehatsite — APPROVED** [review]
Looks good!
