### PR TITLE
Switch to yauzl for unzipping files without loading everything into memory

### LINKED ISSUE #800: Importing large tables and Jetpack backups over 2 GB fail
### Quick summary

A user is attempting to import a Jetpack backup into Studio, which is ~3.7GB. It fails on various tables. Some of them are large with over 1 million rows. When I remove the tables it's failing on from the backup, .zip, and attempt to import again, it returns `ERR_FS_FILE_TOO_LARGE` and appears to have a 2 GB limit. This warning isn't displayed with the original tarball though, which logs similar errors as below but for specific tables it fails on.

Additionally, attempting to only import the database dump, which is ~1.6GB fails with:
```
[2025-01-11T16:18:55.437Z][erro][main] Warning during import of /var/folders/tv/2__tfdjn4r7252t_xdg4_kj00000gn/T/studio_backupF5cgqw/backup_db.sql: wp-cli command canceled
[2025-01-11T16:18:55.447Z][erro][main] Error occurred in handler for 'importSite': Error: Database import failed
    at t.SQLImporter.<anonymous> (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2388219)
    at Generator.next (<anonymous>)
    at o (/Applications/Studio.app/Contents/Resources/app.asar/.webpack/main/index.js:2:2386920)
```

User report: 9260467-zd-a8c

### Steps to reproduce

1. Start Studio app
2. Select an existing site
3. Select Import/Export
4. Attempt to import a large database dump or large Jetpack backup

### What you expected to happen

The backup to import.

### What actually happened

Import process is canceled. 

### Impact

Some (< 50%)

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by ashfame**
## Related issues

- Fixes #800

## Proposed Changes

- Remove `adm-zip` lib in favor of `yauzl` which is more mature & adheres to spec tightly
- Read zip file without loading it all into memory 

## Testing Instructions

- Import a 2GB+ back up file. I tested with a 8.93GB file.

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: src/lib/import-export/import/handlers/backup-handler-zip.ts [hunk 1]
```diff
@@ -1,41 +1,92 @@
...
+							progress: processedSize / totalSize,
+						} as BackupExtractProgressEventData );
+					} );
+
+					writeStream.on( 'finish', () => {
+						zipFile.readEntry();
+					} );
+
+					readStream.pipe( writeStream );
+				} );
```
Comment (fredrikekelund) [inline src/lib/import-export/import/handlers/backup-handler-zip.ts]:
```suggestion
				const readStream = await openReadStream( entry );
				const writeStream = fs.createWriteStream( fullPath );

				readStream.on( 'data', ( chunk ) => {
					processedSize += chunk.length;
					this.emit( ImportEvents.BACKUP_EXTRACT_PROGRESS, {
						progress: processedSize / totalSize,
					} as BackupExtractProgressEventData );
				} );

				writeStream.on( 'finish', () => {
					zipFile.readEntry();
				} );

				readStream.pipe( writeStream );
```
Since we've already imported `promisify`, it'd be nice to do something like this.

File: src/lib/import-export/import/handlers/backup-handler-zip.ts [hunk 2]
```diff
@@ -1,41 +1,92 @@
...
+				resolve( fileNames );
+			} );
+
+			zipFile.on( 'error', reject );
+			zipFile.readEntry();
+		} );
 	}
 
 	async extractFiles( file: BackupArchiveInfo, extractionDirectory: string ): Promise< void > {
+		const zipFile = await openZip( file.path, { lazyEntries: true } );
```
Comment (fredrikekelund) [inline src/lib/import-export/import/handlers/backup-handler-zip.ts:36]:
```suggestion
		const zipFile = await openZip( file.path, { lazyEntries: true } );
		const openReadStream = promisify( zipFile.openReadStream.bind( zipFile ) );
```
And something like this for promisifying `openReadStream`

File: src/lib/import-export/import/handlers/backup-handler-zip.ts [hunk 3]
```diff
@@ -1,41 +1,92 @@
 import { EventEmitter } from 'events';
-import AdmZip from 'adm-zip';
+import * as fs from 'fs';
+import * as path from 'path';
+import { promisify } from 'util';
+import * as fse from 'fs-extra';
+import * as yauzl from 'yauzl';
```
Comment (fredrikekelund) [inline src/lib/import-export/import/handlers/backup-handler-zip.ts]:
```suggestion
import fs from 'fs';
import path from 'path';
import { promisify } from 'util';
import fse from 'fs-extra';
import yauzl from 'yauzl';
```
It's my fault that ESLint's `import/no-named-as-default-member` rule is enabled (happened in https://github.com/Automattic/studio/pull/825). I would advocate disabling that rule in `.eslintrc.json`. This import syntax looks foreign, and I struggle to see how it improves things for us in practice.

**Review by fredrikekelund — APPROVED** [review]
Looks great and works as expected 👍

For completeness sake (I'm currently working on https://github.com/Automattic/dotcom-forge/issues/7611), I can also confirm that the new tests also pass on Windows.

**Review by wojtekn — APPROVED** [review]
Looks good. Make sense to implement improvements proposed by @fredrikekelund , though.

**Comment by ashfame** [comment]
@fredrikekelund Thanks for the detailed code review! ❤️
