### PR TITLE
Override default `umask` in PHP

### LINKED ISSUE #269: Permission issues using a theme that uses composer
### Quick summary

I don't know if this is related to the new [implementation regarding the PHP selector](https://github.com/Automattic/studio/pull/225#pullrequestreview-2112704565), but as soon as I tried to use it I found permission issues. 

Here's the screenshot:
Screenshot 2024-06-17 at 8 26 10 p m

I tried to do the following to fix the issue:
```
# check the permissions
ls -l ../../cache/acorn/framework/cache/
total 0
drwxr-xr-x  2 lajennylove  staff  64 Jun 17 20:26 data
----------  1 lajennylove  staff   0 Jun 17 20:26 packages.php

# change change them
chmod -R 755 ../../cache/acorn/framework/cache/

# Then I tried to change the owner but then that wouldn't have access my self, I guess
chown -R www-data:www-data ../../cache/acorn/framework/cache/
```
Then I though it wouldn't work and I stopped trying. 

### Steps to reproduce

1. Create a new site on Studio
2. Switch to PHP 8.2
3. Clone this Sage/Vite theme https://github.com/DevArge/sage-vite
4. Before activating it, to do the following:
```
# Install vendor
composer install
# Install Vite
yarn 
# Build the assets
yarn build
```
5. Then activate the theme, or even better... Just try to live previewing it to avoid having issues with a broken theme.

### What you expected to happen

The theme gets activated with no issues like if you were using any other LAMP environment.

### What actually happened

I get the following error and I think it could affect to all the users that require composer's cache packages or related:

```
Warning: require(/var/www/html/wp-content/cache/acorn/framework/cache/packages.php): Failed to open stream: Permission denied in /var/www/html/wp-content/themes/sage-vite/vendor/illuminate/filesystem/Filesystem.php on line 123

Fatal error: Uncaught Error: Failed opening required '/var/www/html/wp-content/cache/acorn/framework/cache/packages.php' (include_path='.:') in /var/www/html/wp-content/themes/sage-vite/vendor/illuminate/filesystem/Filesystem.php:123 Stack trace: #0 /var/www/html/wp-content/themes/sage-vite/vendor/illuminate/filesystem/Filesystem.php(124): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}() #1 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Illuminate/Foundation/PackageManifest.php(111): Illuminate\Filesystem\Filesystem->getRequire('/var/www/html/w...') #2 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Illuminate/Foundation/PackageManifest.php(90): Illuminate\Foundation\PackageManifest->getManifest() #3 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Illuminate/Foundation/PackageManifest.php(79): Illuminate\Foundation\PackageManifest->config('aliases') #4 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/RegisterFacades.php(25): Illuminate\Foundation\PackageManifest->aliases() #5 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(263): Roots\Acorn\Bootstrap\RegisterFacades->bootstrap(Object(Roots\Acorn\Application)) #6 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Illuminate/Foundation/Http/Kernel.php(186): Illuminate\Foundation\Application->bootstrapWith(Array) #7 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(187): Illuminate\Foundation\Http\Kernel->bootstrap(Object(Illuminate\Http\Request)) #8 /var/www/html/wp-content/themes/sage-vite/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(103): Roots\Acorn\Bootloader->bootHttp() #9 /var/www/html/wp-content/themes/sage-vite/functions.php(43): Roots\Acorn\Bootloader->boot() #10 /var/www/html/wp-settings.php(663): include('/var/www/html/w...') #11 /var/www/html/wp-config.php(96): require_once('/var/www/html/w...') #12 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...') #13 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #14 /var/www/html/wp-admin/customize.php(13): require_once('/var/www/html/w...') #15 {main} thrown in /var/www/html/wp-content/themes/sage-vite/vendor/illuminate/filesystem/Filesystem.php on line 123
```

### Impact

Most (> 50%)

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by fluiddot**
Related to 8816-gh-Automattic/dotcom-forge.

## Proposed Changes

- The original issue needs to be fixed in Emscripten. There's already [a PR](https://github.com/emscripten-core/emscripten/pull/22589) to address it but it will take time until the changes will be incorporated in the app, as we'll need to wait for new Emscripten and Playground versions.
- ~~In the meantime, we'll create an internal plugin that will override the default `umask` value. Note that this plugin is located in a special folder managed by Playground for platform-level-specific plugins.~~
- As a temporary workaround, we'll override the default `umask` value by pretending a PHP file using the `auto_prepend_file` PHP directive.

### Create files with test file

- Run the app with the command `npm start`.
- Create a new site or select one already created.
- Create the file `test.php`, at the root level on the site, with the following content:
```php
<?php
// Create file with default umask
$filename = "example-default-umask.txt";
$current_umask = umask();
    echo sprintf("Current umask: %04o<br>", $current_umask);
    $content = 'This is the content of the file.';
if (file_exists($filename)) {
    unlink($filename);
}
if (file_put_contents($filename, $content) !== false) {
    echo "File '$filename' created successfully.<br>";
} else {
    echo "Error creating file '$filename'.<br>";
}
chmod($filename, 0777 - umask());
```
- Start the site.
- Navigate to the PHP file: `http://localhost:<PORT>/test.php`.
- Observe the `umask` value shown on the page is `0022`.
- Navigate to the site folder.
- Observe that the permissions of the file are `rwxr-xr-x` (Full access to owner, and only READ and EXECUTE permissions to group and others).

### Addresses https://github.com/Automattic/studio/issues/269

- Start the app with command `npm start`.
- Create a new site.
- Change the PHP version to 8.2.
- Click on the Terminal button.
- In the terminal:
  - Run `cd wp-content/themes`.
  - Run `git clone https://github.com/DevArge/sage-vite.git`.
  - Run `cd sage-vite`.
  - Run `yarn install && composer install && yarn build`.
- Back in the Studio app, start the site.
- Navigate to WP-Admin dashboard.
- Navigate to Appearance -> Themes.
- Activate the Sage Vite theme.
- Observe that no errors are thrown and the site is working as expected.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

File: vendor/wp-now/src/wp-now.ts [hunk 1]
```diff
@@ -109,6 +113,11 @@ export default async function startWPNow(
 		await activatePluginOrTheme( php, options );
 	}
 
+	// Setup internal plugins needed for Playground
+	await setupPlatformLevelMuPlugins( php );
```
Comment (fluiddot) [inline vendor/wp-now/src/wp-now.ts]: [This function is called when booting WordPress in Playground.](https://github.com/WordPress/wordpress-playground/blob/a55dcc01dcb7ac62b6ea7b99949e01b01f4e92cd/packages/playground/wordpress/src/boot.ts#L138)

File: vendor/wp-now/src/wp-now.ts [hunk 2]
```diff
@@ -563,3 +572,15 @@ export async function moveDatabasesInSitu( projectPath: string ) {
 		fs.rmSync( wpContentPath, { recursive: true, force: true } );
 	}
 }
+
+function addDefaultUmaskPlugin( php: PHP, documentRoot: string ) {
+	php.writeFile(
+		'/internal/shared/mu-plugins/override-default-umask.php',
```
Comment (fluiddot) [inline vendor/wp-now/src/wp-now.ts]: All plugins in `/internal/shared/mu-plugins` are loaded by Playground ([reference](https://github.com/WordPress/wordpress-playground/blob/a55dcc01dcb7ac62b6ea7b99949e01b01f4e92cd/packages/playground/wordpress/src/index.ts#L33-L47)). Placing internal plugins in this location will avoid including them when exporting the site.

File: vendor/wp-now/src/wp-now.ts [hunk 3]
```diff
@@ -563,3 +572,15 @@ export async function moveDatabasesInSitu( projectPath: string ) {
...
+		`<?php
+function set_default_umask()
+{
+    umask(0022);
+}
+add_action('init', 'set_default_umask', -9999);`
```
Comment (fluiddot) [inline vendor/wp-now/src/wp-now.ts]: The plugin is executed with the higher priority to ensure the `umask` is set before other plugins.

File: vendor/wp-now/src/wp-now.ts (hunk 2 above)
Comment (wojtekn) [reply vendor/wp-now/src/wp-now.ts]: Should we add an issue to move other polyfill plugins there? It wouldn't change anything now, because we don't include mu-plugins during export, but may be relevant when we start.

**Comment by fluiddot** [comment]
Heads up that this solution won't fix 8818-gh-Automattic/dotcom-forge. More info in https://github.com/Automattic/dotcom-forge/issues/8818#issuecomment-2368833340.

File: vendor/wp-now/src/wp-now.ts (hunk 2 above)
Comment (fluiddot) [reply vendor/wp-now/src/wp-now.ts]: > Should we add an issue to move other polyfill plugins there? It wouldn't change anything now, because we don't include mu-plugins during export, but may be relevant when we start.

Yeah, sounds good. I think we could move all the current plugins we add to `mu-plugins` folder. However, I'd like to note that `/internal/shared/mu-plugins` is not a permanent folder, so we'd need to copy the plugins every time the server starts.

**Comment by fluiddot** [comment]
Following [this comment](https://github.com/Automattic/dotcom-forge/issues/8816#issuecomment-2370584545), I'm going to implement a different approach to override the `umask` value. Until it's ready, I'll change the PR to draft 🔧 .

File: vendor/wp-now/src/wp-now.ts (hunk 2 above)
Comment (fluiddot) [reply vendor/wp-now/src/wp-now.ts]: For reference, here's the issue: https://github.com/Automattic/dotcom-forge/issues/9235

**Review by wojtekn — APPROVED** [review]
It fixes the issue for me. I was able to fix the broken Sage site:

```
rm -rf wp-content/cache
cd wp-content/themes/sage-vite 
yarn install && composer install && yarn build
```

**Comment by lajennylove** [comment]
Hey there guys! 

I was just wondering (because I'm seen this is already merged) when is this going to be available in production studio? Because I opened this ticket https://github.com/Automattic/studio/issues/269#event-14378933473 and it said it was going to be taken care over here. Nevertheless even having the latest Studio version, with PHP 8.3

Screenshot 2024-11-11 at 10 31 33 a m

This is still happening. 
Screenshot 2024-11-11 at 10 32 28 a m

Best regards.

**Comment by wojtekn** [comment]
@lajennylove thanks for retesting it. We fixed the permissions issue, so the directory should have the correct ones when it's created, but if your directory was created before, it will likely still have incorrect permissions.

Please try removing that cache directory and trying again.

**Comment by lajennylove** [comment]
Hey @wojtekn!

I just tested it as you mentioned and it completely worked.

Screenshot 2024-11-11 at 1 27 59 p m

I will try with a real project that I'm working with it to check its relability, and if it works I will implemented it in my company as part of our local development stack. 

Just a quick question (I know this is not the channel maybe and I have to raise other ticket but) I was just wondering if is there a way to control the .htaccess/nginx rules to try something like this?

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^wp-content/uploads/(.*)$ https://www.domain.com/wp-content/uploads/$1 [R=301,L]
</IfModule>
```

Best regards.

**Comment by wojtekn** [comment]
@lajennylove thanks for confirming that.

> Just a quick question (I know this is not the channel maybe and I have to raise other ticket but) I was just wondering if is there a way to control the .htaccess/nginx rules to try something like this?

No, Studio currently doesn't support Apache-like rewrite rules.
